### ISSUE TITLE
Failed to start the server after last update

### ISSUE THREAD

**Issue by endrju81** [pritunl/pritunl#101]
After last update, server wont start on ubuntu 14.04 x64

[evening-stars-9402][2015-05-07 12:11:05,062][ERROR] Failed to apply iptables routing rule
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance.py", line 334, in set_iptables_rules
    retcode, cmd, output=err_out)
CalledProcessError: Command '['iptables', '-A', 'INPUT', '-i', 'tun19', '-j', 'ACCEPT', '-m', 'comment', '--comment', u'pritunl_18ad75db73c6479487f3bebeda36f171']' returned non-zero exit status 4
  output    = 'Another app is currently holding the xtables lock. Perhaps you want to use the -w option?\n'
  server_id = u'18ad75db73c6479487f3bebeda36f171'
  rule      = ['FORWARD', '-i', 'tun19', '-o', 'eth0', '-m', 'state', '--state', 'ESTABLISHED,RELATED', '-j', 'ACCEPT', '-m', 'comment', '--comment', u'pritunl_18ad75db73c6479487f3bebeda36f171']
[evening-stars-9402][2015-05-07 12:11:05,102][ERROR] Server error occurred while running
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance.py", line 530, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance.py", line 334, in set_iptables_rules
    retcode, cmd, output=err_out)
CalledProcessError: Command '['iptables', '-A', 'INPUT', '-i', 'tun19', '-j', 'ACCEPT', '-m', 'comment', '--comment', u'pritunl_18ad75db73c6479487f3bebeda36f171']' returned non-zero exit status 4
  server_id = u'18ad75db73c6479487f3bebeda36f171'
[evening-stars-9402][2015-05-07 12:11:11,491][ERROR] Exception on /server/18ad75db73c6479487f3bebeda36f171/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/server.py", line 699, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/server.py", line 778, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': u'18ad75db73c6479487f3bebeda36f171'}
[evening-stars-9402][2015-05-07 12:11:11,491][ERROR] Exception on /server/18ad75db73c6479487f3bebeda36f171/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/dist-packages/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/handlers/server.py", line 699, in server_operation_put
    svr.start()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/server.py", line 778, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': u'18ad75db73c6479487f3bebeda36f171'}

**Comment by endrju81** [comment]
There seems to be a problem on 3.13.0-51-generic

**Comment by endrju81** [comment]
on on 3.13.0-49-generic and on 3.13.0-52-generic working fine

**Comment by thebenwaters** [comment]
@endrju81 is this a mongo version?
