### ISSUE TITLE
Server no longer run after a few days of work

### ISSUE THREAD

**Issue by yarreg** [pritunl/pritunl#108]
Hello, 
I use the server version: 1.2.604.38
MongoDB: 3.0.3
After few days of work, I rebooted server hardware forced.
After restarting pritunl OpenVPN server no longer run.

When I click on start button the following error occurred:
![image](https://cloud.githubusercontent.com/assets/998319/7777978/ea721888-00cf-11e5-8996-68996f8f950a.png)
In the list of processes no OpenVPN

The log file contains the following error message:
<pre>
 Exception on /server/5555bb9de360b90014707563/start [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.2.604.38-py2.7.egg/pritunl/auth/app.py", line 13, in _wrapped
    return call(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.2.604.38-py2.7.egg/pritunl/handlers/server.py", line 722, in server_operation_put
    svr.start()
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.2.604.38-py2.7.egg/pritunl/server/server.py", line 786, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('5555bb9de360b90014707563')}
</pre>

I'm a little researched the code and found the reason why the server has ceased to be run.
https://github.com/pritunl/pritunl/blob/master/pritunl/runners/server.py#L17
Given condition when checking the returns True and goes to "return" (line 18).
If I comment this code, the OpenVPN server is started normally.

Thanks.

**Comment by zachhuff386** [comment]
The host_id on your server changed it is stored in `/var/lib/pritunl/pritunl.uuid`. When this happens a new host will be created and starting the server will attempt to run it on the host that is offline. This is done for the enterprise edition which supports multiple hosts. For now you will need to edit the host_id in the database or restore the previous host_id and save it in `/var/lib/pritunl/pritunl.uuid`

**Comment by zachhuff386** [comment]
The commit above will fix the servers on startup
