### ISSUE TITLE
API issue - Download a users key tar archive

### ISSUE THREAD

**Issue by makerling** [pritunl/pritunl#112]
I'm having trouble getting either of the following API calls to work. Are they deprecated in the latest undocumented version or am I missing something?

GET /key/:organization_id/:user_id.tar
- result is nothing, expected result is that the user's key tar archive is downloaded to the current directory

GET /key/:organization_id/:user_id
- result is:

Traceback (most recent call last):
  File "pyscripts/pythonscript_get_config.py", line 37, in <module>
    print response.json()
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 740, in json
    return json.loads(self.content.decode(encoding), **kwargs)
  File "/usr/lib/python2.7/dist-packages/simplejson/__init__.py", line 488, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python2.7/dist-packages/simplejson/decoder.py", line 389, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Thanks.

**Comment by zachhuff386** [comment]
The api code is in the `pritunl/handlers` directory which should be used to reference the available api calls and responses. The error above is most likely an authentication issue.
