### ISSUE TITLE
MongoDB not starting

### ISSUE THREAD

**Issue by ossvirt** [pritunl/pritunl#123]
Pritunl startup screen on https://10.x.x.x:9700/ gives MongoDB error -:
```
Unable to connect to MongoDB server.
```
Pritunl installed exactly as per [documentation](https://medium.com/pritunl-tutorials/pritunl-tutorial-ed50a5d2a4eb) on a brand new Ubuntu 14.04.2 64bit server, upgraded and rebooted before Pritunl installation.

Pritunl log shows -:

```
[undefined][2015-06-29 15:04:30,328][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/setup/__init__.py", line 53, in setup_db
    setup_mongo()
  File "/usr/lib/python2.7/dist-packages/pritunl/setup/mongo.py", line 23, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 264, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/python2.7/dist-packages/pymongo/uri_parser.py", line 230, in split_hosts
    raise ConfigurationError("Empty host "
ConfigurationError: Empty host (or extra comma in host list).
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.3.651.28', 'console_scripts', 'pritunl')()
  File "/usr/lib/python2.7/dist-packages/pritunl/__main__.py", line 86, in main
    setup.setup_db()
  File "/usr/lib/python2.7/dist-packages/pritunl/setup/__init__.py", line 53, in setup_db
    setup_mongo()
  File "/usr/lib/python2.7/dist-packages/pritunl/setup/mongo.py", line 23, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT)
  File "/usr/lib/python2.7/dist-packages/pymongo/mongo_client.py", line 264, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/python2.7/dist-packages/pymongo/uri_parser.py", line 230, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).
```
Is there something else I should install or do before installing Pritunl?

**Comment by zachhuff386** [comment]
Run `pritunl reconfigure` and `service pritunl restart` to correct the the MongoDB url. It can also be modified in `/etc/pritunl.com`

**Comment by ossvirt** [comment]
The commands worked as expected but the Pritunl database setup page still gives the same error
```
Unable to connect to MongoDB server.
```
What is going on here? What shall I do at the start to avoid this?
