### ISSUE TITLE
Error when using high-ascii in usernames when encoding keys.

### ISSUE THREAD

**Issue by DaiTengu** [pritunl/pritunl#127]
I have a user with the last name "Gobé"  

After creating the user, and when trying to download keys, I receive this error:

[evening-waves-9869][2015-07-09 18:53:36,584][ERROR] Exception on /key/8951f09d2d7147f5a4a8790016432d8a/553b4bb41668db0d81167812.key [GET]
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/handlers/key.py", line 152, in user_linked_key_conf_get
    key_conf = user.build_key_conf(server_id)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/user/user.py", line 434, in build_key_conf
    include_user_cert)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/user/user.py", line 360, in _generate_conf
    conf_hash.update(self.name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 9: ordinal not in range(128)

The web interface throws a 500 error as well.

**Comment by DaiTengu** [comment]
Workaround is to replace high-ascii characters with something else.   eg: 'é' with 'e'
