### ISSUE TITLE
Error parsing client connect

### ISSUE THREAD

**Issue by yarreg** [pritunl/pritunl#132]
Hello,
I updated to the latest master branch.
When a client connects this error occurs:

```python
[2015-07-17 15:33:14,213][ERROR] Error parsing client connect
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.3.662.15-py2.7.egg/pritunl/server/instance_com.py", line 192, in client_connect
    self.client_ip_insert(user, client_id, virt_address)
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.3.662.15-py2.7.egg/pritunl/server/instance_com.py", line 448, in client_ip_insert
    self.users_ip_collection.update({
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.3.662.15-py2.7.egg/pritunl/helpers.py", line 24, in __get__
    value = self.func(objtype)
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.3.662.15-py2.7.egg/pritunl/server/instance_com.py", line 52, in users_ip_collection
    return mongo.get_collection('users_ip')
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.3.662.15-py2.7.egg/pritunl/mongo/__init__.py", line 14, in get_collection
    return collections[name]
KeyError: 'users_ip'
  instance_id = ObjectId('55a8f5bfaf97d800186a3c0c')
  server_id   = ObjectId('55a8eeac9380f40017001b40')
^CTraceback (most recent call last):
  File "/usr/local/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.3.662.15', 'console_scripts', 'pritunl')()
```

**Comment by zachhuff386** [comment]
Using code directly from the repo isn't supported, the database layout is being modified right now. You will need to use a released version and delete the pritunl database from mongodb which will be corrupted  from using the unfinished code on repo.
