### ISSUE TITLE
Server Crashing Hourly

### ISSUE THREAD

**Issue by benmaynard11** [pritunl/pritunl#146]
Hi,

Not sure where else to raise this issue.

I am facing the following issue every day, multiple times a day. Unsure why. Could you advise?

https://ray465b.images.uk.maynardnetworks.com/4d002a19de9bd0f9fc1e14a79324f16c.png

**Comment by zachhuff386** [comment]
Check the server logs and the logs from command pritunl logs

**Comment by robotiv** [comment]
I am also seeing frequent crashes of OpenVPN visible in the dashboard.

OpenVPN output shows:

calm-plains-3091] Wed Aug 19 12:35:23 2015 Initialization Sequence Completed
[calm-plains-3091] Wed Aug 19 12:35:26 2015 event_wait : Interrupted system call (code=4)
[calm-plains-3091] Wed Aug 19 12:35:26 2015 /sbin/ip addr del dev tun84 192.168.218.1/24
[calm-plains-3091] Wed Aug 19 12:35:26 2015 SIGINT[hard,] received, process exiting
[calm-plains-3091] Wed Aug 19 12:35:30 2015 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
[calm-plains-3091] Wed Aug 19 12:35:30 2015 Control Channel Authentication: tls-auth using INLINE static key file
[calm-plains-3091] Wed Aug 19 12:35:30 2015 SIGINT[hard,init_instance] received, process exiting
[calm-plains-3091] Wed Aug 19 12:35:31 2015 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
[calm-plains-3091] Wed Aug 19 12:35:31 2015 Control Channel Authentication: tls-auth using INLINE static key file
[calm-plains-3091] Wed Aug 19 12:35:31 2015 SIGINT[hard,init_instance] received, process exiting
[calm-plains-3091] Wed Aug 19 12:35:31 2015 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
[calm-plains-3091] Wed Aug 19 12:35:31 2015 Signal received from management interface, exiting
[calm-plains-3091] Wed Aug 19 12:35:33 2015 OpenVPN 2.3.2 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec  1 2014
[calm-plains-3091] Wed Aug 19 12:35:33 2015 Control Channel Authentication: tls-auth using INLINE static key file
[calm-plains-3091] Wed Aug 19 12:35:33 2015 TUN/TAP device tun78 opened
[calm-plains-3091] Wed Aug 19 12:35:33 2015 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
[calm-plains-3091] Wed Aug 19 12:35:33 2015 /sbin/ip link set dev tun78 up mtu 1500

Any ideas on how to remedy this or what other log information you require?

Thanks for a great product by the way, been using it personally for quite some time.

**Comment by zachhuff386** [comment]
Check the output of `pritunl logs`, also what hosting provider is the pritunl server on?

**Comment by robotiv** [comment]
Thanks for responding so quickly. The pritunl server is on Digital Ocean. Here is the output of the pritunl logs:
[undefined][2015-08-18 21:05:43,631][INFO] Setting db version
  new_ver = '1.3.662.15'
  cur_ver = u'1.3.662.15'
[calm-plains-3091][2015-08-18 21:05:43,860][INFO] Starting server
[calm-plains-3091][2015-08-19 12:34:49,063][ERROR] Server management socket path not found
  instance_id = ObjectId('55d4b00d974549029840e62c')
  socket_path = '/var/run/pritunl_55d4b00d974549029840e62c.sock'
  server_id   = ObjectId('55555d2f9745490a076ea92e')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-plains-3091][2015-08-19 12:35:31,082][ERROR] Server management socket path not found
  instance_id = ObjectId('55d4b02c974549029840e680')
  socket_path = '/var/run/pritunl_55d4b02c974549029840e680.sock'
  server_id   = ObjectId('55566d029745490a076f770d')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-plains-3091][2015-08-19 12:35:34,124][ERROR] Server management socket path not found
  instance_id = ObjectId('55d4b038974549029840e69c')
  socket_path = '/var/run/pritunl_55d4b038974549029840e69c.sock'
  server_id   = ObjectId('55566d029745490a076f770d')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-plains-3091][2015-08-19 12:35:42,827][ERROR] Server management socket path not found
  instance_id = ObjectId('55d4b04a974549029840e6d9')
  socket_path = '/var/run/pritunl_55d4b04a974549029840e6d9.sock'
  server_id   = ObjectId('55555d2f9745490a076ea92e')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()

**Comment by benmaynard11** [comment]
Sorry for delay.


[thawing-refuge-5256][2015-08-19 04:02:25,509][ERROR] Server management socket path not found
  instance_id = ObjectId('55d3f1a8e77ead03ac5e04ce')
  socket_path = '/var/run/pritunl_55d3f1a8e77ead03ac5e04ce.sock'
  server_id   = ObjectId('55b16b27e77ead03cb0a6c0c')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-refuge-5256][2015-08-19 04:12:19,170][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/subscription.py", line 31, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 53, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 50, in _request
    raise httplib.HTTPException(error)
HTTPException: <urlopen error timed out>
[thawing-refuge-5256][2015-08-19 04:12:35,205][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/subscription.py", line 31, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 53, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 50, in _request
    raise httplib.HTTPException(error)
HTTPException: <urlopen error timed out>
[thawing-refuge-5256][2015-08-19 04:18:06,999][ERROR] Failed to check notifications
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/runners/updates.py", line 24, in _check_updates
    response = urllib2.urlopen(request, timeout=60)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error timed out>
[thawing-refuge-5256][2015-08-19 04:27:51,051][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/subscription.py", line 31, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 53, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 50, in _request
    raise httplib.HTTPException(error)
HTTPException: <urlopen error timed out>
[thawing-refuge-5256][2015-08-19 04:28:07,085][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/subscription.py", line 31, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 53, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 50, in _request
    raise httplib.HTTPException(error)
HTTPException: <urlopen error timed out>
[thawing-refuge-5256][2015-08-19 05:28:26,968][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/subscription.py", line 31, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 53, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/request.py", line 50, in _request
    raise httplib.HTTPException(error)
HTTPException: <urlopen error timed out>
[thawing-refuge-5256][2015-08-20 12:57:33,102][ERROR] Server management socket path not found
  instance_id = ObjectId('55d5c095e77ead03ac5f657d')
  socket_path = '/var/run/pritunl_55d5c095e77ead03ac5f657d.sock'
  server_id   = ObjectId('55b16b27e77ead03cb0a6c0c')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()

**Comment by zachhuff386** [comment]
Moving all information for error "Server stopped unexpectedly" to #158
