### ISSUE TITLE
Ubuntu Vivid issue

### ISSUE THREAD

**Issue by omegaes** [pritunl/pritunl#160]
After i have installed pritunl on Ubuntu VPS
when i try to excute : pritun start , i get : 
[undefined][2015-09-12 22:10:25,653][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 188, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 90, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 80, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 728, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[undefined][2015-09-12 22:10:56,228][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 188, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 90, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 80, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 728, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[undefined][2015-09-12 22:11:26,817][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 188, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 90, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 80, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 728, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
[undefined][2015-09-12 22:11:57,393][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 188, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 90, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 80, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 728, in _send_message_with_response
    server = topology.select_server(selector)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 97, in select_servers
    self._error_message(selector))
ServerSelectionTimeoutError: localhost:27017: [Errno 111] Connection refused
^C[undefined][2015-09-12 22:12:06,455][INFO] Stopping server
Alarm clock

**Comment by zachhuff386** [comment]
You're mongodb server is not working
