### ISSUE TITLE
Server error after upgrade to new verson

### ISSUE THREAD

**Issue by 4b3ldu4rt3** [pritunl/pritunl#166]
error on login screen

![image](https://cloud.githubusercontent.com/assets/14261740/9978253/a20b1354-5f1d-11e5-85ca-0d7dd7f39c3c.png)

**Comment by 4b3ldu4rt3** [comment]
[undefined][2015-09-15 12:34:09,299][INFO] Starting setup server
[undefined][2015-09-15 12:34:09,304][INFO] Generating setup server ssl cert
[undefined][2015-09-15 12:36:15,512][INFO] Starting setup server
[undefined][2015-09-15 12:36:15,515][INFO] Generating setup server ssl cert
[undefined][2015-09-15 12:36:29,164][INFO] Setting db version
  new_ver = '1.4.733.12'
  cur_ver = u'1.4.729.19'
[undefined][2015-09-19 22:24:51,471][INFO] Starting setup server
[undefined][2015-09-19 22:24:51,477][INFO] Generating setup server ssl cert
[undefined][2015-09-19 22:24:51,524][INFO] Running 1.5 database upgrade
[undefined][2015-09-19 22:24:51,562][INFO] Setting db version
  new_ver = '1.5.0.0'
  cur_ver = u'1.4.733.12'
[undefined][2015-09-19 22:24:51,575][INFO] Setting db version
  new_ver = '1.5.737.82'
  cur_ver = u'1.5.0.0'

**Comment by zachhuff386** [comment]
Update is building now

**Comment by zachhuff386** [comment]
For future issues use `pritunl logs` for the logs, `/var/log/pritunl.log` is only used for logging when the database is uninitialized or unavailable.

**Comment by 4b3ldu4rt3** [comment]
[summer-thunder-4141][2015-09-19 22:37:35,001][ERROR] Exception on /auth/session [POST]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/auth.py", line 14, in auth_session_post
    admin = auth.check_auth(username, password, remote_addr)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/administrator.py", line 249, in check_auth
    if DUO_AUTH in settings.app.sso and sso_admin:
TypeError: argument of type 'NoneType' is not iterable
[summer-thunder-4141][2015-09-19 22:39:55,801][INFO] Starting server
[summer-thunder-4141][2015-09-19 22:43:08,383][INFO] Starting server

**Comment by 4b3ldu4rt3** [comment]
fixed
thanks
