### ISSUE TITLE
Pritunl setup fails on Vultr CentOS7

### ISSUE THREAD

**Issue by gertitorpe** [pritunl/pritunl#169]
I'm using the installation steps provided here but while pritunl runs great on digitalocean VM it always fails on Vultr machines. Both environments are 1 gb ram and CentOS7. Here is the pritunl logs output from Vultr:

[undefined][2015-09-21 18:14:40,968][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 50, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 18, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 308, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/uri_parser.py", line 225, in split_hosts
    raise ConfigurationError("Empty host "
ConfigurationError: Empty host (or extra comma in host list).
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.5.737.70snapshot', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/__main__.py", line 98, in main
    setup.setup_db()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 50, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 18, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 308, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/uri_parser.py", line 225, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

I have the same result using the latest minimal CentoOS7 ISO and the "built in" Vultr installer

**Comment by zachhuff386** [comment]
MongoDB server isn't correctly setup, check that `localhost` is properly set to `127.0.0.1` and check that the MongoDB server is running.
