### ISSUE TITLE
failed to initialize with mongodb

### ISSUE THREAD

**Issue by pshpsh** [pritunl/pritunl#172]
Hi. I have a trouble.
Debian 7, with systemd, fresh install.

pritunl v1.5.743.11

Sep 25 06:57:30 debian systemd[1]: Starting Pritunl Daemon...
Sep 25 06:57:32 debian systemd[1]: Started Pritunl Daemon.
Sep 25 06:57:33 debian systemd[1]: pritunl.service: main process exited, code=exited, status=1/FAILURE
Sep 25 06:57:33 debian systemd[1]: Unit pritunl.service entered failed state.

[undefined][2015-09-25 07:07:55,124][ERROR] Error occured running transaction actions
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/transaction/transaction.py", line 174, in run_actions
    self._run_actions()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/transaction/transaction.py", line 125, in _run_actions
    collection.execute()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/bulk.py", line 582, in execute
    return self.__bulk.execute(write_concern)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/bulk.py", line 436, in execute
    return self.execute_legacy(sock_info, generator, write_concern)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/bulk.py", line 409, in execute_legacy
    raise BulkWriteError(full_result)
BulkWriteError: batch op errors occurred
  transaction_id = ObjectId('56052b0b6e95520762feaf52')
[undefined][2015-09-25 07:07:55,161][INFO] Changing administrator password
  username = 'pritunl'
[undefined][2015-09-25 07:07:55,162][INFO] Generating auth token
[undefined][2015-09-25 07:07:55,163][INFO] Generating auth secret
[undefined][2015-09-25 07:07:55,164][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 50, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 180, in setup_mongo
    default=True,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/administrator.py", line 117, in commit
    mongo.MongoObject.commit(self, *args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/mongo/object.py", line 148, in commit
    spec, update_doc, upsert=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/patches.py", line 43, in update
    val = update_orig(self, *args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 1958, in update
    check_keys, multi, manipulate, write_concern)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 555, in _update
    return sock_info.legacy_write(request_id, msg, max_size, safe)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 237, in legacy_write
    return helpers._check_gle_response(response)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/helpers.py", line 228, in _check_gle_response
    raise OperationFailure(details["err"], code, result)
OperationFailure: Mod on _id not allowed

**Comment by pshpsh** [comment]
all works with special pritunl repo in readme
