### ISSUE TITLE
"Unknown server error occurred." during Database setup

### ISSUE THREAD

**Issue by zgrimz** [pritunl/pritunl#173]
Installed Pritunl and loaded up the webGUI for login at https://myserverip:9700.

When I try to setup the MongoDB URI, I get the error "Unknown server error occurred."

When I refresh the page, it refused my connection. 

Any fix for this?

I've already reloaded my VPS with a fresh install of Ubuntu, but still no luck.
![pritunl issue](https://cloud.githubusercontent.com/assets/14850533/10117987/8840a8e2-6438-11e5-9f27-7e3e0558fed5.png)

Here's the server log
[undefined][2015-09-26 10:24:57,333][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 50, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 27, in setup_mongo
    cur_collections = database.collection_names()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 106, in select_servers
    self._condition.wait(common.MIN_HEARTBEAT_INTERVAL)
  File "/usr/lib/python2.7/threading.py", line 358, in wait
    _sleep(delay)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.5.743.11', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 98, in main
    setup.setup_db()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 50, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 27, in setup_mongo
    cur_collections = database.collection_names()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/database.py", line 488, in collection_names
    ReadPreference.PRIMARY) as (sock_info, slave_okay):
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 699, in _socket_for_reads
    with self._get_socket(read_preference) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 663, in _get_socket
    server = self._get_topology().select_server(selector)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 121, in select_server
    address))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/topology.py", line 106, in select_servers
    self._condition.wait(common.MIN_HEARTBEAT_INTERVAL)
  File "/usr/lib/python2.7/threading.py", line 358, in wait
    _sleep(delay)

**Comment by zgrimz** [comment]
I figured it out. 

The issue was with mongodb and my VPS specs. 

Fixed the issue by enabled smallfiles in the mongodb config file.
