### ISSUE TITLE
Error parsing client connect

### ISSUE THREAD

**Issue by zgrimz** [pritunl/pritunl#175]
If a client is connected for a long time, it seems to disconnect them, resulting in this error.

<code>[ERROR] Error parsing client connect
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/client                                                                                                                                                             s.py", line 265, in connect
    self.allow_client(client, org, user)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/client                                                                                                                                                             s.py", line 135, in allow_client
    'address_dynamic': address_dynamic,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/docdb.py", li                                                                                                                                                             ne 134, in insert
    raise KeyError('Doc id already exists')
KeyError: 'Doc id already exists'
  server_id = ObjectId('56081e16d6515b2d486a248f')</code>
    
Any ideas on how to fix this?

**Comment by zgrimz** [comment]
I think I've narrowed it down to an issue with the TLS handshake and initiates every hour, but I haven't found a solution yet.
I have doubled checked to make sure the TLS Auth Key is correct, and even tired multiple users but it still disconnects me after an hour.

**Comment by zachhuff386** [comment]
Fix will be included in v1.7
