### ISSUE TITLE
Pritunl in docker

### ISSUE THREAD

**Issue by Pauzie** [pritunl/pritunl#176]
I can not start a vpn server inside docker container. I install it on ubuntu trusty with the "new" method, not via ppa. 

I tried it very often, with different settings for the docker container and the pritunl server - without success.

The following comes from "pritunl logs":
[autumn-thunder-5328][2015-09-29 21:08:16,619][ERROR] Exception on /server/xxxxxxxxxx/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 793, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 912, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('xxxxxxxxxx')}

What can i do? Thanks.

--------------------------------------------------------------------------------------------------------
Solve this. Add iptables to the docker container.

**Comment by thebenwaters** [comment]
@Pauzie what did you end up doing? Adding iptables to docker container? Any rules or literally just installing?
