### ISSUE TITLE
Unable to use latest version?

### ISSUE THREAD

**Issue by zoeysiadevelopment** [pritunl/pritunl#184]
I've installed pritunl on 4 installs, and each time it will let me do server setup and create a server, organization, and a user, however after I try to start the server, it consumes all host memory (all 4gb), as well as half of a 1gb swap file. It's the latest version on ubuntu. I pulled the following out of logs.

[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:47:23,813][0m[1;94m[INFO][0m Starting server
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:47:56,680][0m[1;94m[INFO][0m Changing administrator password
  username = u'pritunl'
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:49:12,080][0m[1;91m[ERROR][0m Error running task in queue
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 251, in run
    self.task()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/assign_ip_pool.py", line 90, in task
    self.network_start, self.network_end, self.network_hash)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/ip_pool.py", line 220, in assign_ip_pool
    ip_pool = self.get_ip_pool(network, network_start)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/ip_pool.py", line 42, in get_ip_pool
    ip_pool.next()
StopIteration
  queue_type = u'assign_ip_pool'
  queue_id   = ObjectId('562b9a683c731d05f33db3cb')
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:49:16,904][0m[1;91m[ERROR][0m Exception on /server/562b9a683c731d05f33db3c5/organization/562b9a493c731d05f33db390 [PUT]
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 590, in server_org_put
    svr.commit(svr.changed)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 497, in commit
    self.ip_pool.assign_ip_pool_org(org_id)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/ip_pool.py", line 128, in assign_ip_pool_org
    ip_pool.next()
StopIteration
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:49:16,904][0m[1;91m[ERROR][0m Exception on /server/562b9a683c731d05f33db3c5/organization/562b9a493c731d05f33db390 [PUT]
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 590, in server_org_put
    svr.commit(svr.changed)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 497, in commit
    self.ip_pool.assign_ip_pool_org(org_id)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/ip_pool.py", line 128, in assign_ip_pool_org
    ip_pool.next()
StopIteration
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:49:38,964][0m[1;93m[WARNING][0m Tried to run assign_ip_pool task queue but server is no longer available
  server_id = ObjectId('562b9a683c731d05f33db3c5')
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/runners/queue.py", line 108, in run_queue_item
    queue_item.run()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 251, in run
    self.task()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/assign_ip_pool.py", line 66, in task
    server_id=self.server_id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 49, in warning
    kwargs['traceback'] = traceback.format_stack()
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:49:38,966][0m[1;93m[WARNING][0m Tried to run assign_ip_pool complete queue but server is no longer available
  server_id = ObjectId('562b9a683c731d05f33db3c5')
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/runners/queue.py", line 108, in run_queue_item
    queue_item.run()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 286, in run
    self.complete_task()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/assign_ip_pool.py", line 140, in complete_task
    server_id=self.server_id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 49, in warning
    kwargs['traceback'] = traceback.format_stack()
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:51:55,550][0m[1;91m[ERROR][0m Server management socket path not found
  instance_id = ObjectId('562b9afe3c731d05f33db446')
  socket_path = '/var/run/pritunl_562b9afe3c731d05f33db446.sock'
  server_id   = ObjectId('562b9a863c731d05f33db3e0')
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 215, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 261, in connect
    self.wait_for_socket()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 166, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 56, in error
    kwargs['traceback'] = traceback.format_stack()
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:51:55,555][0m[1;91m[ERROR][0m Error in management socket thread
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 215, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 263, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
  instance_id = ObjectId('562b9afe3c731d05f33db446')
  socket_path = '/var/run/pritunl_562b9afe3c731d05f33db446.sock'
  server_id   = ObjectId('562b9a863c731d05f33db3e0')
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:55:36,529][0m[1;94m[INFO][0m Starting server
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 09:56:06,531][0m[1;91m[ERROR][0m Instance doc lost, stopping server
  server_id = ObjectId('562b9a863c731d05f33db3e0')
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 38, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 649, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 56, in error
    kwargs['traceback'] = traceback.format_stack()
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 10:00:47,095][0m[1;94m[INFO][0m Starting server
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 10:02:24,160][0m[1;91m[ERROR][0m Exception on /server/562b9d6a3c731d02c2662545/start [PUT]
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 793, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 912, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('562b9d6a3c731d02c2662545')}
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 10:02:24,160][0m[1;91m[ERROR][0m Exception on /server/562b9d6a3c731d02c2662545/start [PUT]
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 793, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 912, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('562b9d6a3c731d02c2662545')}
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 10:02:31,052][0m[1;91m[ERROR][0m Instance doc lost, stopping server
  server_id = ObjectId('562b9d6a3c731d02c2662545')
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 38, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 649, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 56, in error
    kwargs['traceback'] = traceback.format_stack()
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 10:02:55,499][0m[1;91m[ERROR][0m Exception on /server/562b9d6a3c731d02c2662545/start [PUT]
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 793, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 912, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('562b9d6a3c731d02c2662545')}
[1;92m[patient-thunder-1965][0m[1m[2015-10-24 10:02:55,499][0m[1;91m[ERROR][0m Exception on /server/562b9d6a3c731d02c2662545/start [PUT]
[1;91mTraceback (most recent call last):[0m
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 793, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 912, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('562b9d6a3c731d02c2662545')}

htop: http://i.imgur.com/YT7bZlm.png

**Comment by zachhuff386** [comment]
What linux distro is being used?

**Comment by siadevelopment** [comment]
ubuntu 14.03

**Comment by zachhuff386** [comment]
Corrupted database is causing the errors, likely an issue with the system.

**Comment by siadevelopment** [comment]
but on four brand new OS installs, 3 with the default pritunl mongodb
install, one with a dedicated mongodb install on another PC?

**Comment by zachhuff386** [comment]
What are the steps followed to get the error from when the OS is installed?

**Comment by dazzert** [comment]
Hi first i hope I am posting this in the right place i did a search and this seemed like the right place to post this error.This morning my Pritunl servers logs showed this , everything is working perfectly right now but i want to know what happened and how to fix it.
Server stopped unexpectedly "server-01-nl". 9:28 am - Dec 24 2015
Server stopped unexpectedly "server-01-uk". 9:28 am - Dec 24 2015
Server stopped unexpectedly "server-01-us". 9:28 am - Dec 24 2015

Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

pritunl v1.12.828.76

I have been getting this error a lot in the pritunl logs 
[ERROR] Instance doc lost, stopping server

I formatted and reloaded from scratch a suspect server and the issue seemed to have gone and the suspect server was not one of those servers that rebooted this morning.I have included the recent log and any help to understand whats going on here would be greatly appreciated .

[patient-forest-4019][2015-12-23 05:40:49,866][INFO] Starting server
[calm-stars-6159][2015-12-23 06:41:26,618][INFO] Starting server
[calm-stars-6159][2015-12-23 07:01:21,020][INFO] Starting server
[autumn-forest-7064][2015-12-23 15:54:24,989][INFO] Starting server
[evening-waves-2902][2015-12-23 14:57:29,193][INFO] Starting server
[calm-stars-6159][2015-12-23 21:28:10,374][ERROR] Instance doc lost, stopping server
  server_id = ObjectId('5679d90d64b36a0222ac6d78')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 38, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 677, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-stars-6159][2015-12-23 21:28:13,146][ERROR] Instance doc lost, stopping server
  server_id = ObjectId('56773cbcb9610e03bca247ab')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 38, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 677, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-stars-6159][2015-12-23 21:28:27,081][ERROR] Failed to update server ping
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 670, in _keep_alive_thread
    }, new=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/patches.py", line 90, in find_and_modify
    val = find_and_modify_orig(self, *args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 2303, in find_and_modify
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 714, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/server.py", line 152, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 536, in get_socket
    sock_info = self._get_socket_no_auth()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 574, in _get_socket_no_auth
    sock_info = self._check(sock_info)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 624, in _check
    return self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 509, in connect
    _raise_connection_failure(self.address, error)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 64, in _raise_connection_failure
    raise AutoReconnect(msg)
AutoReconnect: c56.cockney.5.mongolayer.com:10056: [Errno -2] Name or service not known
  server_id = ObjectId('5677469ab9610e03bca24a09')
[calm-stars-6159][2015-12-23 21:28:27,946][ERROR] Error in transaction runner thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/runners/transaction.py", line 21, in _check_thread
    for doc in collection.find(spec).sort('priority'):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1097, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 1019, in _refresh
    self.__read_concern))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/cursor.py", line 850, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 794, in _send_message_with_response
    exhaust)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 805, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/server.py", line 88, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/server.py", line 152, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 536, in get_socket
    sock_info = self._get_socket_no_auth()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 574, in _get_socket_no_auth
    sock_info = self._check(sock_info)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 624, in _check
    return self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 509, in connect
    _raise_connection_failure(self.address, error)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 64, in _raise_connection_failure
    raise AutoReconnect(msg)
AutoReconnect: c56.cockney.5.mongolayer.com:10056: [Errno -2] Name or service not known
[calm-stars-6159][2015-12-23 21:28:37,252][ERROR] Instance doc lost, stopping server
  server_id = ObjectId('5677469ab9610e03bca24a09')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 38, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 677, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-stars-6159][2015-12-23 21:29:18,725][ERROR] Error running task
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/task.py", line 67, in run
    if not self.claim_commit():
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/task.py", line 54, in claim_commit
    }, upsert=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/patches.py", line 43, in update
    val = update_orig(self, *args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/collection.py", line 2230, in update
    with self._socket_for_writes() as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 714, in _get_socket
    with server.get_socket(self.__all_credentials) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/server.py", line 152, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 536, in get_socket
    sock_info = self._get_socket_no_auth()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 570, in _get_socket_no_auth
    sock_info, from_pool = self.connect(), False
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 509, in connect
    _raise_connection_failure(self.address, error)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/pool.py", line 64, in _raise_connection_failure
    raise AutoReconnect(msg)
AutoReconnect: c56.cockney.5.mongolayer.com:10056: [Errno -2] Name or service not known
  task_type = 'server'
  task_id   = ObjectId('567b584e10112e0ab474010b')

**Comment by zachhuff386** [comment]
Your server is losing connectivity to the MongoDB server causing the server instances to timeout

**Comment by dazzert** [comment]
3 Servers going down , culprit would be the database provider ? I am 
using compose.io hosted in London i see what happens over next few days 
, then if its a issue i will contact them.
Cheers
