### ISSUE TITLE
Clients cannot connect

### ISSUE THREAD

**Issue by agottschling** [pritunl/pritunl#189]
Every time a Android or iOS client attempts to connect, the following error is displayed. However, when I attempt to connect using Viscosity, the connection is successful. Any ideas as to what is going on?

```
[thriving-thunder-5242][2015-11-06 08:58:02,507][ERROR] Error parsing client connect
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/clients.py", line 420, in connect
    self.allow_client(client, org, user, reauth)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/clients.py", line 243, in allow_client
    for client in self.clients.find({'mac_addr': mac_addr}):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/docdb.py", line 110, in find
    return self._find(query, slow)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/docdb.py", line 62, in _find
    raise IndexError('Non indexed query')
IndexError: Non indexed query
  server_id = ObjectId('552d09eefd125719c342ef3e')
```

**Comment by zachhuff386** [comment]
Fixed in commit above will be in next release.

**Comment by agottschling** [comment]
Thanks, Any idea when that will be?

**Comment by zachhuff386** [comment]
Later today this issue can be avoided by disabling mutli device in vpn settings.

**Comment by agottschling** [comment]
Thanks. I'll just wait for the update later today.
