### ISSUE TITLE
ImportError: No module named datetime

### ISSUE THREAD

**Issue by Whax** [pritunl/pritunl#196]
Hi, on a fresh install if I try to start pritunl i've got the following error 
*ImportError: No module named datetime*

```
root@xxx:/# sudo /etc/init.d/pritunl start
Starting service...
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.8.787.62', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 337, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 2279, in load_entry_point
    return ep.load()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/distribute-0.6.24-py2.7.egg/pkg_resources.py", line 1989, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__init__.py", line 1, in <module>
    from pritunl import patches
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/patches.py", line 1, in <module>
    from pritunl.constants import *
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/constants.py", line 2, in <module>
    import datetime
ImportError: No module named datetime
Service started
```

I'm on debian 8, Python 2.7.9 installed.

Thanks for support.

Best regards,

Marc

**Comment by Whax** [comment]
Humm closed so ? :p

**Comment by DavidVentura** [comment]
Same here on Debian8
fixed with 
```bash
cp $(which python2.7) /usr/lib/pritunl/local/bin/python 
```

**Comment by Whax** [comment]
Thank you very much ! :)
