### ISSUE TITLE
Pritunl won't work on debian wheezy

### ISSUE THREAD

**Issue by BeliaevVladimir** [pritunl/pritunl#249]
Linux q 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u2 x86_64 GNU/Linux
pritunl version is 1.16.881.14-0debian1~wheezy all 
I installed a clean debian with openssl and installed pritunl after this
After service start

root@q:~# pritunl logs
[undefined][2016-02-12 08:45:22,492][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 58, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 43, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 326, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 247, in split_hosts
    raise ConfigurationError("Empty host "
ConfigurationError: Empty host (or extra comma in host list).
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.16.881.14', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 188, in main
    setup.setup_db()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 58, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 43, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 326, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 247, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

**Comment by BeliaevVladimir** [comment]
pritunl version is 1.16.881.14-0debian1~wheezy all

**Comment by BeliaevVladimir** [comment]
I installed a clean debian with openssl and installed pritunl after this

**Comment by BeliaevVladimir** [comment]
not enough dependencies
