### ISSUE TITLE
Pritunl won't start correctly after service stop

### ISSUE THREAD

**Issue by g-arjones** [pritunl/pritunl#261]
When Pritunl service is stopped with a SIGTERM it won't bring bridges down and flush added iptables rules. Then when you start it again it will try to setup a bridge over an already bridged interface and pretty much everything else will fail from there

**Comment by adamsewell** [comment]
I believe I'm seeing the same issue. Were you able to work around this?

**Comment by g-arjones** [comment]
I don't think there is a way around this other then flushing iptables and stoping the bridge manually. It is up to the devs to properly clean everything up when a SIGTERM is received. I could implement this myself but I don't think @zachhuff386 would accept my pull request though. Let's hope he fix this eventually.

**Comment by adamsewell** [comment]
How are you flushing iptables are stopping the bridge? I'm wondering if I am seeing the same issue or something else.

**Comment by zachhuff386** [comment]
Recent changes broke the global interrupter for the server instance this will be fixed in the next release

**Comment by adamsewell** [comment]
This may be a dumb question, how do I apply this updated file? Running Ubuntu 14.04.

**Comment by zachhuff386** [comment]
The file is `/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance.py`

**Comment by g-arjones** [comment]
Unfortunately that didn't fix it. After a service pritunl restart:

[winter-skies-6905][2016-02-24 00:40:12,675][ERROR] Popen returned error exit code
  cmd         = ['brctl', 'addif', 'brbreth0', 'breth0']
  return_code = 1
Process stderr:
  device breth0 is a bridge device itself; can't enslave a bridge device to a bridge device.
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance.py", line 880, in _run_thread
    self.bridge_start()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/instance.py", line 262, in bridge_start
    self.interface,
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/bridge.py", line 261, in add_interface
    bridge.start()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/server/bridge.py", line 73, in start
    host_interface,
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 173, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()

**Comment by g-arjones** [comment]
My bad. That was due to cached objects. It works indeed, thank you for the fix.
