### ISSUE TITLE
Problems with IPTables NAT

### ISSUE THREAD

**Issue by LoliHook** [pritunl/pritunl#268]
[guarded-refuge-4806][2016-03-04 12:50:25,533][ERROR] Failed to apply iptables routing rule
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 669, in set_iptables_rules
    self.set_ip6tables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 550, in set_ip6tables_rule
    utils.check_output_logged(['ip6tables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    return_code, cmd, output=stdoutdata)
CalledProcessError: Command '['ip6tables', '-I', 'POSTROUTING', '-t', 'nat', '-o', 'venet0', '-j', 'MASQUERADE', '-s', 'fd00:c0a8:e200::/64', '-m', 'comment', '--comment', 'pritunl_56d8b4a8f8d3b609f49abaa1', '--wait']' returned non-zero exit status 3
  output    = ''
  server_id = ObjectId('56d8b4a8f8d3b609f49abaa1')
[guarded-refuge-4806][2016-03-04 12:50:25,533][ERROR] Popen returned error exit code
  cmd         = ['ip6tables', '-I', 'POSTROUTING', '-t', 'nat', '-o', 'venet0', '-j', 'MASQUERADE', '-s', 'fd00:c0a8:e200::/64', '-m', 'comment', '--comment', 'pritunl_56d8b4a8f8d3b609f49abaa1', '--wait']
  return_code = 3
Process stderr:
  ip6tables v1.4.21: can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)
  Perhaps ip6tables or your kernel needs to be upgraded.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 886, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 669, in set_iptables_rules
    self.set_ip6tables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 550, in set_ip6tables_rule
    utils.check_output_logged(['ip6tables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 146, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[guarded-refuge-4806][2016-03-04 12:50:25,573][ERROR] Server error occurred while running
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 886, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 669, in set_iptables_rules
    self.set_ip6tables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 550, in set_ip6tables_rule
    utils.check_output_logged(['ip6tables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    return_code, cmd, output=stdoutdata)
CalledProcessError: Command '['ip6tables', '-I', 'POSTROUTING', '-t', 'nat', '-o', 'venet0', '-j', 'MASQUERADE', '-s', 'fd00:c0a8:e200::/64', '-m', 'comment', '--comment', 'pritunl_56d8b4a8f8d3b609f49abaa1', '--wait']' returned non-zero exit status 3
  server_id = ObjectId('56d8b4a8f8d3b609f49abaa1')
[guarded-refuge-4806][2016-03-04 12:50:37,987][ERROR] Exception on /server/56d8b4a8f8d3b609f49abaa1/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 938, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 1112, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('56d8b4a8f8d3b609f49abaa1')}
[guarded-refuge-4806][2016-03-04 12:50:37,987][ERROR] Exception on /server/56d8b4a8f8d3b609f49abaa1/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 938, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 1112, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('56d8b4a8f8d3b609f49abaa1')}

My host recommended me to use SNAT instead of NAT because masquerade isn't virtualized in openvz.

Any solution you have?

**Comment by LoliHook** [comment]
Well i setupped the VPN on other server so no problems anymore.
