### ISSUE TITLE
Can not connect to server.

### ISSUE THREAD

**Issue by vtrenten** [pritunl/pritunl#276]
I install it like the tutorial, but this is what comes up.

> 
[undefined][2016-03-11 00:25:26,077][INFO] Starting setup server
[undefined][2016-03-11 00:25:26,084][INFO] Generating setup server ssl cert
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1980, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2052, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 56, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 241, in __init__
    ciphers)
SSLError: [Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1980, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2052, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 56, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 241, in __init__
    ciphers)
SSLError: [Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1980, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2052, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 56, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 241, in __init__
    ciphers)
SSLError: [Errno 336265218] _ssl.c:355: error:140B0002:SSL routines:SSL_CTX_use_PrivateKey_file:system lib

How can i fix this

**Comment by zachhuff386** [comment]
Upgrade to v1.20
