### ISSUE TITLE
Popen returned error exit code

### ISSUE THREAD

**Issue by pottsi** [pritunl/pritunl#281]
Hi,

I've been trying to set up pritunl on a container for the last couple of days. The setup all goes well, i login, create a server and organisation and link them both. when starting the server i get

[thawing-meadow-7006] Sun Mar 13 07:57:30 2016 Server conf:
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   port 19376
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   proto udp
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   dev tun14
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   server 10.0.0.1 255.255.255.0
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   management /var/run/pritunl_56e555aae4da3b015e0ed160.sock unix
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   management-client-auth
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   auth-user-pass-optional
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   topology subnet
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   max-clients 4096
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   ping 10
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   ping-restart 80
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   push "ping 10"
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   push "ping-restart 60"
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   persist-tun
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   cipher AES-256-CBC
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   auth SHA256
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   status-version 2
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   script-security 2
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   reneg-sec 3600
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   hash-size 1024 1024
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   max-routes-per-client 512
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   verb 4
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   mute 8
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   client-to-client
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   replay-window 128
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   comp-lzo no
[thawing-meadow-7006] Sun Mar 13 07:57:30 2016   push "comp-lzo no"

[thawing-meadow-7006][2016-03-13 07:59:16,774][ERROR] Popen returned error exit code
  cmd         = ['iptables', '-I', 'INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']
  return_code = 1
Process stderr:
  iptables: No chain/target/match by that name.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 909, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 558, in set_iptables_rule
    utils.check_output_logged(['iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 146, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-meadow-7006][2016-03-13 07:59:16,775][ERROR] Failed to insert iptables rule, retrying...
  rule = ['INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 909, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 566, in set_iptables_rule
    rule=rule,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-meadow-7006][2016-03-13 07:59:17,783][ERROR] Popen returned error exit code
  cmd         = ['iptables', '-I', 'INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']
  return_code = 1
Process stderr:
  iptables: No chain/target/match by that name.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 909, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 558, in set_iptables_rule
    utils.check_output_logged(['iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 146, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-meadow-7006][2016-03-13 07:59:17,783][ERROR] Failed to insert iptables rule, retrying...
  rule = ['INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 909, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 566, in set_iptables_rule
    rule=rule,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-meadow-7006][2016-03-13 07:59:18,792][ERROR] Failed to apply iptables routing rule
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 558, in set_iptables_rule
    utils.check_output_logged(['iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    return_code, cmd, output=stdoutdata)
CalledProcessError: Command '['iptables', '-I', 'INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']' returned non-zero exit status 1
  output    = ''
  server_id = ObjectId('56e555a2e4da3b015e0ed151')
[thawing-meadow-7006][2016-03-13 07:59:18,794][ERROR] Popen returned error exit code
  cmd         = ['iptables', '-I', 'INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']
  return_code = 1
Process stderr:
  iptables: No chain/target/match by that name.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 524, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 909, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 558, in set_iptables_rule
    utils.check_output_logged(['iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 146, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-meadow-7006][2016-03-13 07:59:18,824][ERROR] Server error occurred while running
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 909, in _run_thread
    self.set_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 680, in set_iptables_rules
    self.set_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 558, in set_iptables_rule
    utils.check_output_logged(['iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    return_code, cmd, output=stdoutdata)
CalledProcessError: Command '['iptables', '-I', 'INPUT', '-i', 'tun13', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56e555a2e4da3b015e0ed151']' returned non-zero exit status 1
  server_id = ObjectId('56e555a2e4da3b015e0ed151')
[thawing-meadow-7006][2016-03-13 07:59:31,844][ERROR] Exception on /server/56e555a2e4da3b015e0ed151/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 976, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 1155, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('56e555a2e4da3b015e0ed151')}
[thawing-meadow-7006][2016-03-13 07:59:31,844][ERROR] Exception on /server/56e555a2e4da3b015e0ed151/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 976, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 1155, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('56e555a2e4da3b015e0ed151')}

I have tun0 enabled and iptables in the vz.conf as:

IPTABLES="iptable_nat ipt_REJECT ipt_tos ipt_limit ipt_multiport iptable_filter iptable_mangle ipt_TCPMSS ipt_tcpmss ipt_ttl ipt_length ipt_LOG ip_conntrack ip_conntrack_ftp ip_conntrack_irc ipt_state ipt_conntrack ipt_helper iptable_na$
#IPTABLES="ipt_REJECT ipt_tos ipt_limit ipt_multiport iptable_filter iptable_mangle ipt_TCPMSS ipt_tcpmss ipt_ttl ipt_length iptable_nat ipt_state"

Is there something i'm doing wrong?

Many thanks.

**Comment by glotzkowski** [comment]
same here :(

`Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.19.913.28', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 252, in main
    pritunl.init_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__init__.py", line 21, in init_server
    app.run_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 208, in run_server
    _run_wsgi_debug()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 186, in _run_wsgi_debug
    threaded=True,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 772, in run
    run_simple(host, port, self, **options)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/werkzeug/serving.py", line 691, in run_simple
    inner()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/werkzeug/serving.py", line 653, in inner
    fd=fd)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/werkzeug/serving.py", line 541, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/werkzeug/serving.py", line 461, in __init__
    HTTPServer.__init__(self, (host, int(port)), handler)
  File "/usr/lib/python2.7/SocketServer.py", line 419, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 430, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
`

**Comment by pottsi** [comment]
Your issue looks a little different to mine, what's your server setup like? is it a container, vm , etc. I think we should be able to fix yours, I'm at a total lose with mine :)

**Comment by zachhuff386** [comment]
The issue is with the virtual machine or host. Pritunl will not be able to run on that.

**Comment by pottsi** [comment]
Before closing the question could you give some details on why it won't run?

**Comment by zachhuff386** [comment]
I'm not sure exactly what is wrong with it, the issue is related to the OpenVZ setup not Pritunl.

**Comment by pottsi** [comment]
Have you experienced this on other openvz setups? Would it make a difference if I set it up as a vm instead of a container?
