### ISSUE TITLE
Can't update above 1.3.651.28

### ISSUE THREAD

**Issue by sankros** [pritunl/pritunl#285]
Hi there. First I want to say thank you for a great job.

Until now, I used **version 1.0.586.29**, mongod 2.6.3
I want to upgrade, because I have a problem with "_Server stopped unexpectedly_"

When I installed the latest version, I could not run the service

_service pritunl start:_
`start: Job failed to start`

_pritunl version / pritunl logs:_
`-bash: / usr / bin / pritunl: / usr / lib / pritunl / bin / python: bad interpreter: No such file or directory`

_service pritunl_
`pritunl: unrecognized service`

_service pritunl status_
`pritunl stop / waiting`

I installed manually pritunl_1.0.586.29-0ubuntu1.trusty_all.deb package and service earned again. After that I began to install versions in the release order. The latest version, which runs on my server - **1.3.651.28**. When I install **1.3.662.15 or any newer version**, I get the error described.

I want to upgrade to at least version 1.5.743.11 to get rid of the "_Server stopped unexpectedly_"

Please tell me what to do.

_System information:_

```
openvpn --version
OpenVPN 2.3.2 i686-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [eurephia] [MH] [IPv6] built on Dec January 2014
Originally developed by James Yonan
Copyright (C) 2002-2010 OpenVPN Technologies, Inc. <Sales@openvpn.net>
Compile time defines: enable_crypto = yes enable_debug = yes enable_def_auth = yes enable_dependency_tracking = no enable_dlopen = unknown enable_dlopen_self = unknown enable_dlopen_self_static = unknown enable_eurephia = yes enable_fast_install = yes enable_fragment = yes enable_http_proxy = yes enable_iproute2 = yes enable_libtool_lock = yes enable_lzo = yes enable_lzo_stub = no enable_maintainer_mode = no enable_management = yes enable_multi = yes enable_multihome = yes enable_pam_dlopen = no enable_password_save = yes enable_pedantic = no enable_pf = yes enable_pkcs11 = yes enable_plugin_auth_pam = yes enable_plugin_down_root = yes enable_plugins = yes enable_port_share = yes enable_selinux = no enable_server = yes enable_shared = yes enable_shared_with_static_runtimes = no enable_small = no enable_socks = yes enable_ssl = yes enable_static = yes enable_strict = no enable_strict_options = no enable_systemd = no enable_win32_dll = yes enable_x509_alt_username = yes with_crypto_library = openssl with_gnu_ld = yes with_ifconfig_path = / sbin / ifconfig with_iproute_path = / sbin / ip with_mem_check = no with_plugindir = '$ {prefix} / lib / openvpn' with_route_path = / sbin / route with_sysroot = no
```

_free -h_
```
             total       used       free     shared    buffers     cached
Mem:          256M       125M       130M       2.6M         0B        86M
-/+ buffers/cache:        38M       217M
Swap:         1.0G         0B       1.0G

```

_cat / etc / * - release_
```
DISTRIB_ID = Ubuntu
DISTRIB_RELEASE = 14.04
DISTRIB_CODENAME = trusty
DISTRIB_DESCRIPTION = "Ubuntu 14.04.4 LTS"
NAME = "Ubuntu"
VERSION = "14.04.4 LTS, Trusty Tahr"
ID = ubuntu
ID_LIKE = debian
PRETTY_NAME = "Ubuntu 14.04.4 LTS"
VERSION_ID = "14.04"
HOME_URL = "http://www.ubuntu.com/"
SUPPORT_URL = "http://help.ubuntu.com/"
BUG_REPORT_URL = "http://bugs.launchpad.net/ubuntu/"
```

**Comment by zachhuff386** [comment]
Run `cat /var/log/pritunl.log` and `pritunl logs`

**Comment by sankros** [comment]
**pritunl v1.3.651.28**

_cat /var/log/pritunl.log_

`[undefined][2016-03-14 18:24:16,073][INFO] Generating server ssl cert
[undefined][2016-03-14 18:24:20,378][INFO] Setting db version
  new_ver = '1.3.651.28'
  cur_ver = u'1.3.651.28'
[undefined][2016-03-14 18:25:40,334][INFO] Setting db version
  new_ver = '1.3.651.28'
  cur_ver = u'1.3.651.28'
`

pritunl logs

`[calm-plateau-6694][2016-03-14 15:02:44,523][INFO] Starting server
[calm-plateau-6694][2016-03-14 15:03:26,545][INFO] Changing administrator password
  username = u'master'
[calm-plateau-6694][2016-03-14 15:04:25,082][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/queue/queue.py", line 256, in run
    self.task()
  File "/usr/lib/python2.7/dist-packages/pritunl/queues/assign_ip_addr.py", line 52, in task
    'queue_type': self.type,
ServerNetworkLocked: Server network is locked. {'server_id': ObjectId('56e70b2612a17c037e10df4d'), 'queue_type': u'assign_ip_addr', 'queue_id': ObjectId('56e70b2f12a17c037e10df64')}
  queue_type = u'assign_ip_addr'
  queue_id   = ObjectId('56e70b2f12a17c037e10df64')
[calm-plateau-6694][2016-03-14 15:04:29,873][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/queue/queue.py", line 256, in run
    self.task()
  File "/usr/lib/python2.7/dist-packages/pritunl/queues/assign_ip_addr.py", line 52, in task
    'queue_type': self.type,
ServerNetworkLocked: Server network is locked. {'server_id': ObjectId('56e70b2612a17c037e10df4d'), 'queue_type': u'assign_ip_addr', 'queue_id': ObjectId('56e70b3312a17c037e10df6b')}
  queue_type = u'assign_ip_addr'
  queue_id   = ObjectId('56e70b3312a17c037e10df6b')
[calm-plateau-6694][2016-03-14 15:09:48,155][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 5Cz3q is not a valid ObjectId
  object_id = u'5Cz3q'
[calm-plateau-6694][2016-03-14 15:48:47,588][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: kn2Mw is not a valid ObjectId
  object_id = u'kn2Mw'
[calm-plateau-6694][2016-03-14 15:50:56,309][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: kn2Mw is not a valid ObjectId
  object_id = u'kn2Mw'
[calm-plateau-6694][2016-03-14 15:51:21,016][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: kn2Mw is not a valid ObjectId
  object_id = u'kn2Mw'
[calm-plateau-6694][2016-03-14 15:52:21,097][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: kn2Mw is not a valid ObjectId
  object_id = u'kn2Mw'
[calm-plateau-6694][2016-03-14 17:16:06,699][INFO] Starting server
[snowy-refuge-8546][2016-03-14 17:23:03,776][INFO] Starting server
[snowy-refuge-8546][2016-03-14 17:24:27,836][INFO] Starting server
[snowy-refuge-8546][2016-03-14 17:26:17,052][INFO] Starting server
[snowy-refuge-8546][2016-03-14 17:29:17,859][INFO] Starting server
[thriving-forest-9872][2016-03-14 17:32:05,586][INFO] Starting server
[thriving-forest-9872][2016-03-14 17:34:46,524][INFO] Starting server
[snowy-thunder-1412][2016-03-14 17:38:37,639][INFO] Starting server
[snowy-dreams-4225][2016-03-14 18:04:49,852][INFO] Starting server
[ancient-waterfall-3201][2016-03-14 18:24:21,059][INFO] Starting server
[ancient-waterfall-3201][2016-03-14 18:25:45,590][INFO] Starting server
[ancient-waterfall-3201][2016-03-14 18:59:23,301][ERROR] Server management socket path not found
  instance_id = ObjectId('56e7421912a17c0156e13b8d')
  socket_path = '/var/run/pritunl_56e7421912a17c0156e13b8d.sock'
  server_id   = ObjectId('56e70b2612a17c037e10df4d')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
[ancient-waterfall-3201][2016-03-14 18:59:24,980][ERROR] Server management socket path not found
  instance_id = ObjectId('56e7423112a17c0156e13b98')
  socket_path = '/var/run/pritunl_56e7423112a17c0156e13b98.sock'
  server_id   = ObjectId('56e70b2612a17c037e10df4d')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 465, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 510, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 409, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/__init__.py", line 59, in error
    kwargs['traceback'] = traceback.format_stack()
`

**After installing 1.3.662.15**
_cat /var/log/pritunl.log_
empty

_pritunl logs_
`-bash: /usr/bin/pritunl: /usr/lib/pritunl/bin/python: bad interpreter: No such file or directory`

**Comment by zachhuff386** [comment]
R

**Comment by zachhuff386** [comment]
What Linux distribution are you using? Try removing the pritunl package and try reinstalling.

**Comment by sankros** [comment]
Ubuntu Server 14.04 x86

I have tried uninstalling and reinstalling pritunl package: the same error occurs.

So I cant install another linux distro on my VPS.

**Comment by zachhuff386** [comment]
You're using 32 bit Pritunl is only packaged for 64 bit.
