### ISSUE TITLE
pritunl fails to start

### ISSUE THREAD

**Issue by vmindru** [pritunl/pritunl#292]
How to reproduce: 

1) Install from the repo 

```
root@ip-:~# cat /etc/apt/sources.list.d/pritunl.list
deb http://repo.pritunl.com/stable/apt trusty mainroot@ip-:~# 
```
2)  try to start pritunl

```
root@ip-:~# pritunl start                                                                                                                                                                               
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.20.917.37', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 221, in main
    from pritunl import settings
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/settings/__init__.py", line 5, in <module>
    sys.modules[__name__] = Settings()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/settings/settings.py", line 24, in __init__
    self._init_modules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/settings/settings.py", line 120, in _init_modules
    group_cls.load()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/settings/group_file.py", line 18, in load
    doc = json.loads(settings_file.read())
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting , delimiter: line 3 column 5 (char 62)
root@ip-:~# cat /etc/apt/sources.list.d/pritunl.list
```

OS details

```
root@ip-:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.4 LTS
Release:        14.04
Codename:       trusty
root@ip-10-15-44-189:~# dpkg --list | grep pritunl
ii  pritunl                                  1.20.917.37-0ubuntu1~trusty      all          Enterprise VPN Server
root@ip-10-15-44-189:~# dpkg --list | grep mongo
ii  mongodb-org                              3.0.10                           amd64        MongoDB open source document-oriented database system (metapackage)
ii  mongodb-org-mongos                       3.0.10                           amd64        MongoDB sharded cluster query router
ii  mongodb-org-server                       3.0.10                           amd64        MongoDB database server
ii  mongodb-org-shell                        3.0.10                           amd64        MongoDB shell client
ii  mongodb-org-tools                        3.0.10                           amd64        MongoDB tools
root@ip-:~# 



```

**Comment by zachhuff386** [comment]
The config file `/etc/pritunl.conf` isn't valid json, check the file with a json validator.

**Comment by vmindru** [comment]
Can we open it , it would be useful to return a proper error rather than a thread dump :)

VM
