### ISSUE TITLE
Server management socket path not found

### ISSUE THREAD

**Issue by svkamp** [pritunl/pritunl#293]
calm-forest-8533][2016-03-17 14:38:11,362][ERROR] Error in management socket thread
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pritunl-1.20.917.37-py2.7.egg/pritunl/server/instance_com.py", line 237, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/site-packages/pritunl-1.20.917.37-py2.7.egg/pritunl/server/instance_com.py", line 319, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib64/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
  instance_id = ObjectId('56eaf988ea2baa2a8aa7df1f')
  socket_path = '/var/run/pritunl_56eaf988ea2baa2a8aa7df1f.sock'
  server_id   = ObjectId('56ea5117ea2baa028a02d473')
[calm-forest-8533][2016-03-17 14:38:21,471][ERROR] Server management socket path not found
  instance_id = ObjectId('56eaf992ea2baa2a8aa7df27')
  socket_path = '/var/run/pritunl_56eaf992ea2baa2a8aa7df27.sock'
  server_id   = ObjectId('56ea5117ea2baa028a02d473')
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/site-packages/pritunl-1.20.917.37-py2.7.egg/pritunl/server/instance_com.py", line 237, in _socket_thread
    self.connect()
  File "/usr/lib/python2.7/site-packages/pritunl-1.20.917.37-py2.7.egg/pritunl/server/instance_com.py", line 317, in connect
    self.wait_for_socket()
  File "/usr/lib/python2.7/site-packages/pritunl-1.20.917.37-py2.7.egg/pritunl/server/instance_com.py", line 177, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/python2.7/site-packages/pritunl-1.20.917.37-py2.7.egg/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[calm-forest-8533][2016-03-17 14:38:21,488][ERROR] Error in management socket thread
Traceback (most recent call last):

**Comment by zachhuff386** [comment]
Most likely SE Linux issue

**Comment by svkamp** [comment]
Yupp appears so... thanks, might want to update the documentation.
