### ISSUE TITLE
Problem installation Ubuntu Trusty

### ISSUE THREAD

**Issue by Gsivade** [pritunl/pritunl#296]
Hello everyone,
since the new release i have lot of troubles for installing pritunl.

This is my "pritunl logs"

But i already have install pymongo..

`[ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 59, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 53, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 326, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 244, in split_hosts
    raise ConfigurationError("Empty host "
ConfigurationError: Empty host (or extra comma in host list).
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.20.917.37', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 125, in main
    setup.setup_db()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 59, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 53, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 326, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 244, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).`

Thanks for helping me!

**Comment by zachhuff386** [comment]
Run `pritunl reconfigure`
