### ISSUE TITLE
"Pritunl setup failed"

### ISSUE THREAD

**Issue by fridaynext** [pritunl/pritunl#302]
I've created a brand new Linode instance with Ubuntu 14.04, and when I set install Pritunl and mongodb-org, on trying to run Pritunl I get this error.  (I also can't access https://my.ip:9700 from the web.

root@horsehead:~# pritunl logs
[undefined][2016-03-28 12:15:27,161][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 59, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 53, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 326, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 244, in split_hosts
    raise ConfigurationError("Empty host "
ConfigurationError: Empty host (or extra comma in host list).
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.21.928.27', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 209, in main
    setup.setup_db()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 59, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 53, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 326, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 244, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).

**Comment by fridaynext** [comment]
I've also run 'pritunl reconfigure', and I still have the same error message.

**Comment by fridaynext** [comment]
After many OS reinstalls of Ubuntu 15.04, 15.10, etc - I finally settled on 14.04.  I installed everything per the instructions again, and this time realized that the default port has changed to 443, rather than 9700.  I got an "Unkown Server Error Occured", then just clicked "Save" again, and it worked.  Now setting up my Pritunl server.
