### ISSUE TITLE
Server timeout error on start

### ISSUE THREAD

**Issue by thebenwaters** [pritunl/pritunl#304]
pritunl v1.21.928.27 in **docker container**

First time server startup
```
[winter-waterfall-1194][2016-04-04 15:43:44,028][ERROR] Exception on /server/57028b3ead92e0000ad9474e/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 980, in server_operation_put
    svr.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/server.py", line 1179, in start
    'server_id': self.id,
ServerStartError: Server start timed out. {'server_id': ObjectId('57028b3ead92e0000ad9474e')}
[winter-waterfall-1194][2016-04-04 18:08:52,638][ERROR] Exception on /server/57028b3ead92e0000ad9474e/start [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/server.py", line 980, in server_operation_put
    svr.start()
```

**Comment by thebenwaters** [comment]
Referencing #101 
Attempted by upgrading kernel to 3.13.0-52-generic and no luck

**Comment by thebenwaters** [comment]
Referencing #108

```
> db.hosts.findOne()
{
        "_id" : "7bbe234dceb34c2e96e6a36c25012da3",
        "status" : "online",
        "start_timestamp" : ISODate("2016-04-04T19:04:49.744Z"),
        "auto_instance_id" : "i-b332bd70",
        "local_address6" : null,
        "name" : "winter-waterfall-1194",
        "auto_local_address6" : "fe80::42:acff:fe11:3",
        "auto_public_address6" : null,
        "routed_subnet6" : null,
        "auto_public_address" : "52.8.4.42",
        "public_address6" : "",
        "auto_local_address" : "172.17.0.3",
        "local_networks" : [
                "172.17.0.0/16"
        ],
        "instance_id" : null,
        "public_address" : "52.8.4.42",
        "link_address" : null,
        "local_address" : null,
        "hostname" : "2f5ab1b1b34e",
        "ping_timestamp" : ISODate("2016-04-04T19:15:15.189Z"),
        "cpu_usage" : 1.2,
        "mem_usage" : 2.3,
        "thread_count" : 48,
        "server_count" : 0,
        "device_count" : 0
}
```
```
cat /var/lib/pritunl/pritunl.uuid
7bbe234dceb34c2e96e6a36c25012da3
```

**Comment by thebenwaters** [comment]
```
> db.servers_output.findOne()
{
        "_id" : ObjectId("5702888dad92e0000a9b0990"),
        "timestamp" : ISODate("2016-04-04T15:30:21.082Z"),
        "server_id" : ObjectId("57028720ad92e0000a9b0852"),
        "output" : "[winter-waterfall-1194] Mon Apr  4 15:30:21 2016 Server conf:"
}
```
Ok it doesn't match here. Is this an issue?

**Comment by thebenwaters** [comment]
Updated all the server_id s in servers_output to match the one server. Still getting same error

**Comment by thebenwaters** [comment]
Just like #176 just installed iptables within the docker image and it worked just fine
