### ISSUE TITLE
Upgrading to v1.21.938.10

### ISSUE THREAD

**Issue by PillowPhone** [pritunl/pritunl#309]
Hello,

Yet another Pritunl upgrade has completely broken the application. Can you please start giving more due care and attention to upgrades as I am fed up of having to roll back from upgrades when they don't work. I never had this issue with OpenVPN Access Server.

Please can you also advise on the below....

```
[summer-meadow-6231][2016-04-07 13:56:10,319][ERROR] Popen returned error exit code
  cmd         = ['iptables', '-I', 'INPUT', '-i', 'tun1', '-d', u'10.67.4.125/32', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56c239dc57b90a0447a18e73']
  return_code = 4
Process stderr:
  Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 736, in _run_thread
    self.iptables.upsert_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 508, in upsert_rules
    self._insert_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 463, in _insert_iptables_rule
    ['ip6tables' if ipv6 else 'iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 146, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[summer-meadow-6231][2016-04-07 13:56:10,321][ERROR] Failed to insert iptables rule, retrying...
  rule = ['INPUT', '-i', 'tun1', '-d', u'10.67.4.125/32', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_56c239dc57b90a0447a18e73']
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 736, in _run_thread
    self.iptables.upsert_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 508, in upsert_rules
    self._insert_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 471, in _insert_iptables_rule
    rule=rule,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[summer-meadow-6231][2016-04-07 13:56:11,637][ERROR] Failed to ping web server
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 223, in _web_watch_thread
    verify=verify,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/request.py", line 68, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/request.py", line 65, in _request
    raise httplib.HTTPException(error)
HTTPException: 'module' object has no attribute 'SSLContext'
  url = 'https://localhost:9700/ping'
[summer-meadow-6231][2016-04-07 13:56:13,642][ERROR] Failed to ping web server
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 223, in _web_watch_thread
    verify=verify,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/request.py", line 68, in get
    return _request('GET', url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/request.py", line 65, in _request
    raise httplib.HTTPException(error)
HTTPException: 'module' object has no attribute 'SSLContext'
  url = 'https://localhost:9700/ping'
[summer-meadow-6231][2016-04-07 13:56:13,643][ERROR] Web server non-responsive, restarting...
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 39, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 246, in _web_watch_thread
    logger.error('Web server non-responsive, restarting...', 'watch')
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()

```

**Comment by zachhuff386** [comment]
Duplicate #310
