### ISSUE TITLE
Error after rebuild docker with last version of pritunl

### ISSUE THREAD

**Issue by Fridus** [pritunl/pritunl#312]
I use `pritunl/archlinux`

```
FROM pritunl/archlinux

RUN echo "[pritunl]" >> /etc/pacman.conf; echo "Server = http://repo.pritunl.com/stable/pacman" >> /etc/pacman.conf
RUN gpg --keyserver hkp://keyserver.ubuntu.com --recv-keys CF8E292A;\
    pacman-key --keyserver hkp://keyserver.ubuntu.com -r CF8E292A; \
    pacman-key --lsign-key CF8E292A; \
    pacman -Sy; \
    pacman -S --noconfirm pritunl
```

On start :
```
Traceback (most recent call last):
  File "/usr/sbin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.21.939.33', 'console_scripts', 'pritunl')()
  File "/usr/lib/python2.7/site-packages/pritunl/__main__.py", line 262, in main
    pritunl.init_server()
  File "/usr/lib/python2.7/site-packages/pritunl/__init__.py", line 18, in init_server
    from pritunl import app
  File "/usr/lib/python2.7/site-packages/pritunl/app.py", line 4, in <module>
    from pritunl import logger
  File "/usr/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 3, in <module>
    from pritunl.logger.handler import LogHandler, log_queue
  File "/usr/lib/python2.7/site-packages/pritunl/logger/handler.py", line 1, in <module>
    from pritunl.logger.view import LogView
  File "/usr/lib/python2.7/site-packages/pritunl/logger/view.py", line 4, in <module>
    from pritunl import utils
  File "/usr/lib/python2.7/site-packages/pritunl/utils/__init__.py", line 7, in <module>
    from pritunl.utils.aws import *
  File "/usr/lib/python2.7/site-packages/pritunl/utils/aws.py", line 4, in <module>
    import boto
ImportError: No module named boto
```

**Comment by zachhuff386** [comment]
Install the python boto module

**Comment by Fridus** [comment]
@zachhuff386  It works ! Thx ! My docker is up to date ;)

But another error is present :
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 157, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
IOError: [Errno 29] Illegal seek
Logged from file __init__.py, line 32
[undefined][2016-04-10 12:05:54,762][INFO] Starting setup server
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 76, in emit
    if self.shouldRollover(record):
  File "/usr/lib/python2.7/logging/handlers.py", line 157, in shouldRollover
    self.stream.seek(0, 2)  #due to non-posix-compliant Windows feature
IOError: [Errno 29] Illegal seek
Logged from file __init__.py, line 32
[undefined][2016-04-10 12:05:54,763][INFO] Generating setup server ssl cert
```
