### ISSUE TITLE
Web server error

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#315]
Hi.
I often have to restart the server, as there is no access to the web panel
---

[restless-plains-5979][2016-04-08 23:11:14,710][ERROR] Failed to ping web server
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/app.py", line 240, in _web_watch_thread
    verify=verify,
  File "/usr/lib/pritunl/lib/python2.7/site-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: EOF occurred in violation of protocol (_ssl.c:765)
  url = 'https://localhost:443/ping'
[restless-plains-5979][2016-04-08 23:11:14,711][ERROR] Web server non-responsive, restarting...
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 784, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib64/python2.7/threading.py", line 811, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 764, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/helpers.py", line 39, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/app.py", line 264, in _web_watch_thread
    logger.error('Web server non-responsive, restarting...', 'watch')
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[restless-plains-5979][2016-04-08 23:11:14,755][INFO] Server restarting...
[restless-plains-5979][2016-04-08 23:11:14,756][INFO] Starting server
[restless-plains-5979][2016-04-08 23:11:14,756][INFO] Generating server dh params...
[restless-plains-5979][2016-04-08 23:11:31,765][ERROR] Server error occurred
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/app.py", line 169, in _run_wsgi
    app_server.start()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1967, in start
    raise socket.error(msg)
error: No socket could be created -- (('0.0.0.0', 443): [Errno 98] Address already in use)
[restless-plains-5979][2016-04-09 07:43:31,414][INFO] Starting redirect server
[restless-plains-5979][2016-04-09 07:43:32,434][INFO] Starting server

**Comment by zachhuff386** [comment]
Fixed in v1.21.941.39
