### ISSUE TITLE
urlib requires certificates to be present [packaging, bug]

### ISSUE THREAD

**Issue by dennybaa** [pritunl/pritunl#347]
Fix: Package must depend on `ca-certificates` on debian systems, as well as on corresponding package on other systems.

```
[snowy-waves-5230][2016-05-11 00:28:45,899][ERROR] Failed to check notifications
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/runners/updates.py", line 23, in _check_updates
    response = urllib2.urlopen(request, timeout=60)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

**Comment by dennybaa** [comment]
also no iptables dependency...

```
[ancient-forest-7137][2016-05-12 17:13:44,118][INFO] Starting server
Exception in thread Thread-1342:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 787, in _run_thread
    self.iptables.clear_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 639, in clear_rules
    self._remove_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 519, in _remove_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by zachhuff386** [comment]
Fixed in https://github.com/pritunl/pritunl-pacur/commit/771742d225934b22f8a9ce6912c3aebea26d5a4f
