### ISSUE TITLE
Issue 1.22

### ISSUE THREAD

**Issue by Gsivade** [pritunl/pritunl#352]
Good morning, I have an error after upgrading to 1.22

`Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.22.977.25', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 132, in main
    from pritunl import setup
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 4, in <module>
    from pritunl.setup.mongo import setup_mongo
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 2, in <module>
    from pritunl import app
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 7, in <module>
    from pritunl import monitoring
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/monitoring/__init__.py", line 3, in <module>
    from pritunl import influxdb
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/influxdb/__init__.py", line 23, in <module>
    from .client import InfluxDBClient
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/influxdb/client.py", line 37, in <module>
    from .line_protocol import make_lines
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/influxdb/line_protocol.py", line 30, in <module>
    from dateutil.parser import parse
ImportError: No module named dateutil.parser
`

Thanks,

**Comment by sha1** [comment]
`sudo /usr/lib/pritunl/bin/pip install python-dateutil`

**Comment by Gsivade** [comment]
Thanks, solved :)
