### ISSUE TITLE
Error downloading Let's Encrypt challenge

### ISSUE THREAD

**Issue by galindro** [pritunl/pritunl#358]
@zachhuff386 I'm having the exatcly same problem reported by @k0nsl on https://github.com/pritunl/pritunl/issues/221. 

In my instance, there isn't any webserver running on tcp port 80 and the port is publicy accessible.
The DNS record is correctly pointing to the instance. I could confirm that the instance can recognize the domain from inside of it by doing a dig.

```bash
$ dig +short mydns.mydomain.com
xx.xxx.xx.xxx
```

```bash
$ pritunl logs
[guarded-fields-2630][2016-05-18 10:25:25,216][INFO] Starting server
[guarded-fields-2630][2016-05-18 10:25:58,583][INFO] Parsing acme account key...
[guarded-fields-2630][2016-05-18 10:25:58,598][INFO] Parsing acme CSR...
[guarded-fields-2630][2016-05-18 10:25:58,614][INFO] Registering acme account...
[guarded-fields-2630][2016-05-18 10:25:59,068][INFO] Registered acme certificate
[guarded-fields-2630][2016-05-18 10:25:59,068][INFO] Verifying acme domain mydns.mydomain.com...
[guarded-fields-2630][2016-05-18 10:25:59,526][ERROR] Failed to get LetsEncrypt cert
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/settings.py", line 541, in settings_put
    acme.update_acme_cert()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 49, in update_acme_cert
    cert = get_acme_cert(settings.app.acme_key, csr)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme.py", line 24, in get_acme_cert
    app.set_acme,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/acme_tiny.py", line 139, in get_crt
    raise ValueError("Couldn't download {0}".format(wellknown_url))
ValueError: Couldn't download http://mydns.mydomain.com/.well-known/acme-challenge/RZpehHq7zIHuOMWVW2PWbtqsU463VKu88jRLlxC9fgo
  acme_domain = u'mydns.mydomain.com'
```

If I try to access that URL, I can see (through tcpdump) that the packages enter into the instance. When configure Let's Encrypt through settings on web interface and click on Save button, I can see network traffic between private and public IP of the instance, but the connection is refused because there isn't 80/tcp port opened:

```bash
~# netstat -tlnp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9756          0.0.0.0:*               LISTEN      23861/python    
tcp        0      0 0.0.0.0:10050           0.0.0.0:*               LISTEN      2869/zabbix_agentd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      2320/sshd       
tcp        0      0 127.0.0.1:27017         0.0.0.0:*               LISTEN      2312/mongod     
tcp        0      0 0.0.0.0:10443           0.0.0.0:*               LISTEN      24208/openvpn   
tcp6       0      0 :::443                  :::*                    LISTEN      23907/pritunl-web
tcp6       0      0 :::10050                :::*                    LISTEN      2869/zabbix_agentd
tcp6       0      0 :::22                   :::*                    LISTEN      2320/sshd       
```

This is my config file:

```bash
$ cat /etc/pritunl.conf 
{
    "mongodb_uri": "mongodb://localhost:27017/pritunl", 
    "log_path": "/var/log/pritunl.log", 
    "static_cache": true, 
    "temp_path": "/tmp/pritunl_45e881586b4e46d09c273b361c461468", 
    "bind_addr": "0.0.0.0", 
    "debug": false, 
    "www_path": "/usr/share/pritunl/www", 
    "local_address_interface": "auto", 
    "port": 443
}
```

How could I debug this?

I could send to you in PVT my domain and my IP address if you want.

**Comment by zachhuff386** [comment]
Open port 80 and set the DNS record to the Pritunl public IP address. The error above indicates you didn't correctly do one of those steps.

**Comment by galindro** [comment]
@zachhuff386 I've pointed the DNS record to the instance and openned the TCP port 80 in the security group, as I said. Could I send to you a PCT message with the dns for you to check?
