### ISSUE TITLE
email of user keys not working

### ISSUE THREAD

**Issue by mklatsky** [pritunl/pritunl#363]
I have configured email using Postmark. When ate,sting to send mail, I receive a timeout. The error log shows:

[thriving-meadow-4872][2016-05-31 16:06:47,442][ERROR] Exception on /user/47e926df789a4590b5d71308cdf9e336/4a5568dd555f45e49fba1fd42b244882 [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/user.py", line 478, in user_put
    user.send_key_email(utils.get_url_root()[:-1])
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 790, in send_key_email
    html_email,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/mail.py", line 31, in send_email
    smtp_conn = smtplib.SMTP_SSL(email_server)
  File "/usr/lib/python2.7/smtplib.py", line 788, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 793, in _get_socket
    new_socket = socket.create_connection((host, port), timeout)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 110] Connection timed out

From the server running pritunl, I am able to get a banner at smtp.postmarkapp.com:

 telnet smtp.postmarkapp.com 25
Trying 50.31.156.99...
Connected to smtp.postmarkapp.com.
Escape character is '^]'.
220 smtp.postmarkapp.com ESMTP sc-ord-smtp1

I am then able to successfully authenticate (auth login using my base64 user/pass).

It seems like, for some reason, Pritunl is unable to connect to smtp.postmarkapp.com, even though other connection methods succeed.

**Comment by zachhuff386** [comment]
The SSL port must be used

**Comment by mklatsky** [comment]
The port shown was an example. The 3 ports from Postmark documentation are 25, 2525 and 587 (http://developer.postmarkapp.com/developer-send-smtp.html)

If my SMTP server setting in the pritunl interface is either smtp.postmarkapp.com or smtp.postmarkapp.com:25, the connection simply times out (although on the command line from the pritunl server, it does *not* timeout). If I set the SMTP server setting in the pritunl interface to smtp.postmarkapp.com:2525 or smtp.postmarkapp.com:587, I get an instant error return stating failure. From my logs:

[thriving-meadow-4872][2016-06-06 15:06:22,842][ERROR] Exception on /user/47e926df789a4590b5d71308cdf9e336/4a5568dd555f45e49fba1fd42b244882 [PUT]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 9, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/user.py", line 478, in user_put
    user.send_key_email(utils.get_url_root()[:-1])
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 790, in send_key_email
    html_email,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/mail.py", line 31, in send_email
    smtp_conn = smtplib.SMTP_SSL(email_server)
  File "/usr/lib/python2.7/smtplib.py", line 788, in __init__
    SMTP.__init__(self, host, port, local_hostname, timeout)
  File "/usr/lib/python2.7/smtplib.py", line 256, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/lib/python2.7/smtplib.py", line 316, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/lib/python2.7/smtplib.py", line 794, in _get_socket
    new_socket = ssl.wrap_socket(new_socket, self.keyfile, self.certfile)
  File "/usr/lib/python2.7/ssl.py", line 487, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 243, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 405, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:510: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
