### ISSUE TITLE
device breth1 is a bridge device itself; can't enslave a bridge device to a bridge device

### ISSUE THREAD

**Issue by tk-s** [pritunl/pritunl#367]
Hi, i have already configured a bridge as he primary Network-Interface and i would like to use bridged mode. But sadly pritunl wants to create a new bridge, wich wont work:

[summer-forest-8113][2016-05-28 23:45:37,221][ERROR] Popen returned error exit code
  cmd         = ['brctl', 'addif', 'brbreth1', 'breth1']
  return_code = 1
Process stderr:
  device breth1 is a bridge device itself; can't enslave a bridge device to a bridge device.
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 738, in _run_thread
    self.bridge_start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 272, in bridge_start
    self.interface,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/bridge.py", line 261, in add_interface
    bridge.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/bridge.py", line 73, in start
    host_interface,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 147, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()

**Comment by zachhuff386** [comment]
Existing bridges can't be used, the bridge will be automatically created.

**Comment by tk-s** [comment]
Why?
If i disable the bridge-creation-code in pritunl/server/bridge.py if the interface in question is already a bridge, pritunl (until now) works just fine...
