### ISSUE TITLE
Another failed upgrade :)

### ISSUE THREAD

**Issue by PillowPhone** [pritunl/pritunl#372]
Whoa, what a shock... another Pritunl upgrade that has failed and rendered the server unusable.

You need to up your game. I cannot explain how fed up I am of botched upgrades causing me issues. You have paying customers and you think that slapping a big tag on the issue and not even commenting is a satisfactory response?

```
summer-meadow-6231][2016-05-21 09:27:41,169][ERROR] Web server process exited unexpectedly
Process stderr:
  panic: listen tcp 0.0.0.0:9700: bind: address already in use
  
  goroutine 1 [running]:
  panic(0x7345e0, 0xc820159590)
  	/usr/local/go/src/runtime/panic.go:481 +0x3e6
  main.main()
  	/go/src/github.com/pritunl/pritunl-web/main.go:119 +0x43a
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 164, in poll_thread
    stderr=stderr,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[summer-meadow-6231][2016-05-21 09:27:43,272][INFO] Server restarting...
[summer-meadow-6231][2016-05-21 09:27:43,273][INFO] Starting server
[summer-meadow-6231][2016-05-22 15:57:41,019][INFO] Server restarting...
[summer-meadow-6231][2016-05-22 15:57:41,021][INFO] Starting server
[summer-meadow-6231][2016-05-22 15:57:44,023][INFO] Server restarting...
[summer-meadow-6231][2016-05-22 15:57:44,024][INFO] Starting server
[summer-meadow-6231][2016-05-22 18:52:16,778][ERROR] Instance doc lost, stopping server
  server_id = ObjectId('565d1b8f57b90a03ff02f8f2')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 39, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 571, in _keep_alive_thread
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[summer-meadow-6231][2016-06-02 17:57:23,120][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/subscription.py", line 40, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='app.pritunl.com', port=443): Read timed out. (read timeout=15)
[summer-meadow-6231][2016-06-02 17:57:39,394][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/subscription.py", line 40, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='app.pritunl.com', port=443): Read timed out. (read timeout=15)
[summer-meadow-6231][2016-06-02 18:12:55,508][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/subscription.py", line 40, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='app.pritunl.com', port=443): Read timed out. (read timeout=15)
[summer-meadow-6231][2016-06-02 18:13:11,773][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/subscription.py", line 40, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='app.pritunl.com', port=443): Read timed out. (read timeout=15)
[summer-meadow-6231][2016-06-02 18:28:27,905][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/subscription.py", line 40, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='app.pritunl.com', port=443): Read timed out. (read timeout=15)
[summer-meadow-6231][2016-06-02 18:28:44,181][ERROR] Failed to check subscription status
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/subscription.py", line 40, in update
    timeout=max(settings.app.http_request_timeout, 10),
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/requests/adapters.py", line 479, in send
    raise ReadTimeout(e, request=request)
ReadTimeout: HTTPSConnectionPool(host='app.pritunl.com', port=443): Read timed out. (read timeout=15)
[undefined][2016-06-11 13:45:42,081][INFO] Starting setup server
[undefined][2016-06-11 13:45:42,103][INFO] No upgrade needed
[undefined][2016-06-11 13:45:42,609][INFO] Setting db version
  new_ver = '1.23.1002.28'
  cur_ver = u'1.22.980.85'
[summer-meadow-6231][2016-06-11 13:45:44,307][INFO] Starting server
[summer-meadow-6231][2016-06-11 13:45:44,625][ERROR] Web server process exited unexpectedly
Process stderr:
  panic: listen tcp 0.0.0.0:9700: bind: address already in use
  
  goroutine 1 [running]:
  panic(0x734500, 0xc820157590)
  	/usr/local/go/src/runtime/panic.go:481 +0x3e6
  main.main()
  	/go/src/github.com/pritunl/pritunl-web/main.go:128 +0x492
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 178, in poll_thread
    stderr=stderr,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[summer-meadow-6231][2016-06-11 13:45:46,734][INFO] Server restarting...
[summer-meadow-6231][2016-06-11 13:45:46,734][INFO] Starting server
[summer-meadow-6231][2016-06-11 13:48:42,854][INFO] Starting server
[summer-meadow-6231][2016-06-11 13:49:13,032][INFO] Starting server
[summer-meadow-6231][2016-06-11 13:51:11,784][WARNING] Open file ulimit is lower then recommended
[summer-meadow-6231][2016-06-11 13:51:11,786][INFO] Starting server
[summer-meadow-6231][2016-06-11 13:52:18,646][WARNING] Open file ulimit is lower then recommended
[summer-meadow-6231][2016-06-11 13:52:18,648][INFO] Starting server
[summer-meadow-6231][2016-06-11 13:56:23,270][INFO] Starting server
```

**Comment by zachhuff386** [comment]
What issue is occurring? The error above can occur when the previous web server process takes too long to exit. It will continue to restart the web server until it opens. It appears it started on the second attempt.

**Comment by paulkramme** [comment]
@PillowPhone Please calm and review your situation. You want something from him, so be friendly and everybody is more willing to help you.
