### ISSUE TITLE
Certificate verification failed: PolarSSL: SSL read error: X509

### ISSUE THREAD

**Issue by teddybugs** [pritunl/pritunl#374]
Hello,

I keep getting PolarSSL error X509 for recent installation, on older version pritunl it work fine without this issue. Tried 2 days to google around and no luck, also installed on centos 7/debian 8/ubuntu 14.04, all face same problem. so i decided to ask here

My vps is KVM based with tun/tap enabled.
DH Param Bits : **2048**
Encryption Cipher: **AES 256 bit**
Hash Algorithm : **SHA-256**

screenshot:
[link 1](https://www.dropbox.com/s/17qomz5htfrv3re/Screenshot_2016-06-13-09-06-32.png?dl=0)
[link 2](https://www.dropbox.com/s/w1k9u0ve8bj0uh9/Screenshot_2016-06-13-09-06-56.png?dl=0)

this is what the log say on debug screen of **Server Output**:
```

[evening-stars-9994] Mon Jun 13 03:55:41 2016 Server conf:
[evening-stars-9994] Mon Jun 13 03:55:41 2016   port 3389
[evening-stars-9994] Mon Jun 13 03:55:41 2016   proto tcp6
[evening-stars-9994] Mon Jun 13 03:55:41 2016   dev tun0
[evening-stars-9994] Mon Jun 13 03:55:41 2016   server 192.168.218.0 255.255.255.0
[evening-stars-9994] Mon Jun 13 03:55:41 2016   server-ipv6 fd00:c0a8:da00::/64
[evening-stars-9994] Mon Jun 13 03:55:41 2016   management /var/run/pritunl_575e66fd3b315d2e0501fcb5.sock unix
[evening-stars-9994] Mon Jun 13 03:55:41 2016   management-client-auth
[evening-stars-9994] Mon Jun 13 03:55:41 2016   auth-user-pass-optional
[evening-stars-9994] Mon Jun 13 03:55:41 2016   topology subnet
[evening-stars-9994] Mon Jun 13 03:55:41 2016   max-clients 60
[evening-stars-9994] Mon Jun 13 03:55:41 2016   ping 60
[evening-stars-9994] Mon Jun 13 03:55:41 2016   ping-restart 80
[evening-stars-9994] Mon Jun 13 03:55:41 2016   push "ping 60"
[evening-stars-9994] Mon Jun 13 03:55:41 2016   push "ping-restart 60"
[evening-stars-9994] Mon Jun 13 03:55:41 2016   persist-tun
[evening-stars-9994] Mon Jun 13 03:55:41 2016   cipher AES-256-CBC
[evening-stars-9994] Mon Jun 13 03:55:41 2016   auth SHA256
[evening-stars-9994] Mon Jun 13 03:55:41 2016   status-version 2
[evening-stars-9994] Mon Jun 13 03:55:41 2016   script-security 2
[evening-stars-9994] Mon Jun 13 03:55:41 2016   reneg-sec 2592000
[evening-stars-9994] Mon Jun 13 03:55:41 2016   hash-size 1024 1024
[evening-stars-9994] Mon Jun 13 03:55:41 2016   max-routes-per-client 512
[evening-stars-9994] Mon Jun 13 03:55:41 2016   verb 4
[evening-stars-9994] Mon Jun 13 03:55:41 2016   mute 8
[evening-stars-9994] Mon Jun 13 03:55:41 2016   client-to-client
[evening-stars-9994] Mon Jun 13 03:55:41 2016   duplicate-cn
[evening-stars-9994] Mon Jun 13 03:55:41 2016   comp-lzo no
[evening-stars-9994] Mon Jun 13 03:55:41 2016   push "comp-lzo no"
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=646945 Current Parameter Settings:
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647011   config = '/tmp/pritunl_fd03299c7464443e88d7b6c0127183e5/99f576f0602d43a3bc88750bcfeb4a58/openvpn.conf'
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647021   mode = 1
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647027   persist_config = DISABLED
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647033   persist_mode = 1
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647038   show_ciphers = DISABLED
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647044   show_digests = DISABLED
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647049   show_engines = DISABLED
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647054 NOTE: --mute triggered...
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647078 273 variation(s) on previous 8 message(s) suppressed by --mute
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647090 OpenVPN 2.3.4 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Nov 12 2015
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=647125 library versions: OpenSSL 1.0.1k 8 Jan 2015, LZO 2.08
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=652313 MANAGEMENT: unix domain socket listening on /var/run/pritunl_575e66fd3b315d2e0501fcb5.sock
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=694632 Diffie-Hellman initialized with 2048 bit key
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=695043 Control Channel Authentication: tls-auth using INLINE static key file
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=695070 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=695080 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=695104 TLS-Auth MTU parms [ L:1572 D:180 EF:80 EB:0 ET:0 EL:0 ]
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=695130 Socket Buffers: R=[87380->131072] S=[16384->131072]
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=740823 TUN/TAP device tun0 opened
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=740889 TUN/TAP TX queue length set to 100
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=740910 do_ifconfig, tt->ipv6=1, tt->did_ifconfig_ipv6_setup=1
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=740940 /sbin/ip link set dev tun0 up mtu 1500
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=751624 /sbin/ip addr add dev tun0 192.168.218.1/24 broadcast 192.168.218.255
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=758987 /sbin/ip -6 addr add fd00:c0a8:da00::1/64 dev tun0
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=764879 Data Channel MTU parms [ L:1572 D:1450 EF:72 EB:135 ET:0 EL:0 AF:3/1 ]
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=764912 Listening for incoming TCP connection on [undef]
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=764949 TCPv6_SERVER link local (bound): [undef]
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=764965 TCPv6_SERVER link remote: [undef]
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=765009 MULTI: multi_init called, r=1024 v=1024
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=765072 IFCONFIG POOL IPv6: (IPv4) size=252, size_ipv6=65536, netbits=64, base_ipv6=fd00:c0a8:da00::1000
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=765087 IFCONFIG POOL: base=192.168.218.2 size=252, ipv6=1
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=765108 MULTI: TCP INIT maxclients=60 maxevents=64
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=765151 Initialization Sequence Completed
[evening-stars-9994] Mon Jun 13 03:55:43 2016 us=765199 MANAGEMENT: Client connected from /var/run/pritunl_575e66fd3b315d2e0501fcb5.sock
[evening-stars-9994] Mon Jun 13 03:55:44 2016 us=655391 MANAGEMENT: CMD 'bytecount 15'
[evening-stars-9994] Mon Jun 13 03:55:44 2016 COM> SUCCESS: bytecount interval changed
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=367252 MULTI: multi_create_instance called
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=367490 Re-using SSL/TLS context
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=367653 LZO compression initialized
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=371819 Control Channel MTU parms [ L:1572 D:180 EF:80 EB:0 ET:0 EL:0 ]
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=371880 Data Channel MTU parms [ L:1572 D:1450 EF:72 EB:135 ET:0 EL:0 AF:3/1 ]
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372001 Local Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-server'
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372012 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client'
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372073 Local Options hash (VER=V4): '165db97f'
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372088 Expected Remote Options hash (VER=V4): '504bba81'
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372204 TCP connection established with [AF_INET6]::ffff:115.164.176.8:19772
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372730 TCPv6_SERVER link local (bound): [undef]
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=372755 TCPv6_SERVER link remote: [AF_INET6]::ffff:115.164.176.8:19772
[evening-stars-9994] Mon Jun 13 04:01:44 2016 us=382807 ::ffff:115.164.176.8 TLS: Initial packet from [AF_INET6]::ffff:115.164.176.8:19772, sid=e84cc4fa 515f02a0
[evening-stars-9994] Mon Jun 13 04:01:50 2016 us=174177 ::ffff:115.164.176.8 Connection reset, restarting [0]
[evening-stars-9994] Mon Jun 13 04:01:50 2016 us=174308 ::ffff:115.164.176.8 SIGUSR1[soft,connection-reset] received, client-instance restarting
[evening-stars-9994] Mon Jun 13 04:01:50 2016 us=174781 TCP/UDP: Closing socket
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=989322 MULTI: multi_create_instance called
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=989489 Re-using SSL/TLS context
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=989574 LZO compression initialized
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990018 Control Channel MTU parms [ L:1572 D:180 EF:80 EB:0 ET:0 EL:0 ]
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990050 Data Channel MTU parms [ L:1572 D:1450 EF:72 EB:135 ET:0 EL:0 AF:3/1 ]
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990167 Local Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-server'
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990176 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client'
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990199 Local Options hash (VER=V4): '165db97f'
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990210 Expected Remote Options hash (VER=V4): '504bba81'
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990298 TCP connection established with [AF_INET6]::ffff:115.164.176.8:49003
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990310 TCPv6_SERVER link local (bound): [undef]
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990317 TCPv6_SERVER link remote: [AF_INET6]::ffff:115.164.176.8:49003
[evening-stars-9994] Mon Jun 13 04:02:32 2016 us=990612 ::ffff:115.164.176.8 TLS: Initial packet from [AF_INET6]::ffff:115.164.176.8:49003, sid=95bdbffa 49db8139
[evening-stars-9994] Mon Jun 13 04:02:38 2016 us=794761 ::ffff:115.164.176.8 Connection reset, restarting [0]
[evening-stars-9994] Mon Jun 13 04:02:38 2016 us=794830 ::ffff:115.164.176.8 SIGUSR1[soft,connection-reset] received, client-instance restarting
[evening-stars-9994] Mon Jun 13 04:02:38 2016 us=794946 TCP/UDP: Closing socket
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=118483 MULTI: multi_create_instance called
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=118660 Re-using SSL/TLS context
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=118721 LZO compression initialized
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=118965 Control Channel MTU parms [ L:1572 D:180 EF:80 EB:0 ET:0 EL:0 ]
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119024 Data Channel MTU parms [ L:1572 D:1450 EF:72 EB:135 ET:0 EL:0 AF:3/1 ]
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119128 Local Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-server'
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119138 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client'
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119165 Local Options hash (VER=V4): '165db97f'
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119178 Expected Remote Options hash (VER=V4): '504bba81'
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119222 TCP connection established with [AF_INET6]::ffff:115.164.176.8:18370
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119233 TCPv6_SERVER link local (bound): [undef]
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=119241 TCPv6_SERVER link remote: [AF_INET6]::ffff:115.164.176.8:18370
[evening-stars-9994] Mon Jun 13 04:08:00 2016 us=126363 ::ffff:115.164.176.8 TLS: Initial packet from [AF_INET6]::ffff:115.164.176.8:18370, sid=a541706f 31a00976
[evening-stars-9994] Mon Jun 13 04:08:05 2016 us=588640 ::ffff:115.164.176.8 Connection reset, restarting [0]
[evening-stars-9994] Mon Jun 13 04:08:05 2016 us=588722 ::ffff:115.164.176.8 SIGUSR1[soft,connection-reset] received, client-instance restarting
[evening-stars-9994] Mon Jun 13 04:08:05 2016 us=588915 TCP/UDP: Closing socket
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632177 MULTI: multi_create_instance called
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632437 Re-using SSL/TLS context
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632495 LZO compression initialized
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632749 Control Channel MTU parms [ L:1572 D:180 EF:80 EB:0 ET:0 EL:0 ]
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632784 Data Channel MTU parms [ L:1572 D:1450 EF:72 EB:135 ET:0 EL:0 AF:3/1 ]
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632871 Local Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-server'
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632893 Expected Remote Options String: 'V4,dev-type tun,link-mtu 1572,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA256,keysize 256,tls-auth,key-method 2,tls-client'
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632922 Local Options hash (VER=V4): '165db97f'
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632935 Expected Remote Options hash (VER=V4): '504bba81'
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632974 TCP connection established with [AF_INET6]::ffff:115.164.176.8:6493
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632985 TCPv6_SERVER link local (bound): [undef]
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=632993 TCPv6_SERVER link remote: [AF_INET6]::ffff:115.164.176.8:6493
[evening-stars-9994] Mon Jun 13 04:09:15 2016 us=641041 ::ffff:115.164.176.8 TLS: Initial packet from [AF_INET6]::ffff:115.164.176.8:6493, sid=c3deed2e da5cf459
[evening-stars-9994] Mon Jun 13 04:09:20 2016 us=962150 ::ffff:115.164.176.8 Connection reset, restarting [0]
[evening-stars-9994] Mon Jun 13 04:09:20 2016 us=962198 ::ffff:115.164.176.8 SIGUSR1[soft,connection-reset] received, client-instance restarting
[evening-stars-9994] Mon Jun 13 04:09:20 2016 us=962282 TCP/UDP: Closing socket
```

and this is the log from "Top Right corner":

```
[undefined][2016-06-13 03:49:19,177][INFO] Starting setup server
[undefined][2016-06-13 03:49:19,180][INFO] Generating setup server ssl cert
[undefined][2016-06-13 03:50:22,832][INFO] Generating auth token
[undefined][2016-06-13 03:50:22,833][INFO] Generating auth secret
[evening-stars-9994][2016-06-13 03:50:23,913][INFO] Starting server
[evening-stars-9994][2016-06-13 03:50:23,920][INFO] Generating server dh params...
[evening-stars-9994][2016-06-13 03:50:24,070][INFO] Generating server certificate...
[evening-stars-9994][2016-06-13 03:50:24,419][ERROR] Web server process exited unexpectedly
Process stderr:
  panic: listen tcp 0.0.0.0:443: bind: address already in use
  
  goroutine 1 [running]:
  panic(0x734500, 0xc820010cd0)
  	/usr/local/go/src/runtime/panic.go:481 +0x3e6
  main.main()
  	/go/src/github.com/pritunl/pritunl-web/main.go:128 +0x492
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 178, in poll_thread
    stderr=stderr,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[evening-stars-9994][2016-06-13 03:50:26,528][INFO] Server restarting...
[evening-stars-9994][2016-06-13 03:50:26,530][INFO] Starting server
[evening-stars-9994][2016-06-13 03:50:26,948][INFO] Server restarting...
[evening-stars-9994][2016-06-13 03:50:26,950][INFO] Starting server
[evening-stars-9994][2016-06-13 03:51:09,971][INFO] Parsing acme account key...
[evening-stars-9994][2016-06-13 03:51:09,994][INFO] Parsing acme CSR...
[evening-stars-9994][2016-06-13 03:51:10,016][INFO] Registering acme account...
[evening-stars-9994][2016-06-13 03:51:10,349][INFO] Registered acme certificate
[evening-stars-9994][2016-06-13 03:51:10,350][INFO] Verifying acme domain server1.mon112.com...
[evening-stars-9994][2016-06-13 03:51:13,139][INFO] Verified acme domain server1.mon112.com
[evening-stars-9994][2016-06-13 03:51:13,139][INFO] Signing acme certificate...
[evening-stars-9994][2016-06-13 03:51:13,456][INFO] Signed acme certificate
[evening-stars-9994][2016-06-13 03:51:17,097][INFO] Server restarting...
[evening-stars-9994][2016-06-13 03:51:17,098][INFO] Starting server
[evening-stars-9994][2016-06-13 03:55:41,706][ERROR] Failed to find default IPv6 interface
  server_id = ObjectId('575e66703b315d2e0501fac5')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 741, in _run_thread
    self.generate_iptables_rules()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 372, in generate_iptables_rules
    server_id=self.server.id,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
```

here is my other server's log that use older version of pritunl which is working fine:
http://pastebin.com/9xCN4Ft7

noticed also on this older server we have:
**[ERROR] Failed to find default IPv6 interface**

this could rule out the problem with IPv6.

any help would be great.

Thanks
David

**Comment by teddybugs** [comment]
I manage to sort it out by reinstall ubuntu using clean version.. but debian and centos still not fixed.
