### ISSUE TITLE
why pritunl always turns itself off and "web server" stops

### ISSUE THREAD

**Issue by safuansatay** [pritunl/pritunl#383]
Why pritunl always turns itself off and "web server" stops
This is my pritunl log

[winter-forest-7209][2016-06-24 09:17:53,014][ERROR] Error in management socket thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 248, in _socket_thread
    self.sock_send('bytecount %s\n' % self.bandwidth_rate)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 45, in sock_send
    self.sock.send(data)
error: [Errno 32] Broken pipe
  instance_id = ObjectId('576d32fef339f706a3c47388')
  socket_path = '/var/run/pritunl_576d32fef339f706a3c47388.sock'
  server_id   = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-24 09:18:00,587][ERROR] Error in management socket thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 246, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 328, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
  instance_id = ObjectId('576d3308f339f706a3c47393')
  socket_path = '/var/run/pritunl_576d3308f339f706a3c47393.sock'
  server_id   = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-24 09:18:10,890][ERROR] Error in management socket thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 246, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 328, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
  instance_id = ObjectId('576d3312f339f706a3c473ff')
  socket_path = '/var/run/pritunl_576d3312f339f706a3c473ff.sock'
  server_id   = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-24 10:20:03,953][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-24 10:31:05,150][INFO] Starting server
[winter-forest-7209][2016-06-24 18:11:04,587][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-24 18:15:08,019][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-24 18:22:33,391][ERROR] Failed to create user cert requests
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 193, in initialize
    self.org.queue_com.popen(args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/com.py", line 32, in popen
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  user_id = ObjectId('576db2a9f339f7036f721bae')
  org_id  = ObjectId('576cdf20f339f706a3c36ce2')
[winter-forest-7209][2016-06-24 18:22:33,646][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 251, in run
    self.task()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/init_user_pooled.py", line 24, in task
    self.user.initialize()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 225, in initialize
    utils.rmtree(temp_path)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 198, in rmtree
    check_output_logged(['rm', '-rf', path])
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  queue_type = u'init_user_pooled'
  queue_id   = ObjectId('576db2a9f339f7036f721baf')
[winter-forest-7209][2016-06-24 18:22:39,946][ERROR] Failed to create user cert requests
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 193, in initialize
    self.org.queue_com.popen(args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/com.py", line 32, in popen
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  user_id = ObjectId('576db2aff339f7036f721bb5')
  org_id  = ObjectId('576cdf20f339f706a3c36ce2')
[winter-forest-7209][2016-06-24 18:22:39,963][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 251, in run
    self.task()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/init_user_pooled.py", line 24, in task
    self.user.initialize()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 225, in initialize
    utils.rmtree(temp_path)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 198, in rmtree
    check_output_logged(['rm', '-rf', path])
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  queue_type = u'init_user_pooled'
  queue_id   = ObjectId('576db2aff339f7036f721bb6')
[winter-forest-7209][2016-06-24 18:22:56,197][ERROR] Failed to create user cert requests
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 193, in initialize
    self.org.queue_com.popen(args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/com.py", line 32, in popen
    stderr=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  user_id = ObjectId('576db2bff339f7036f721bff')
  org_id  = ObjectId('576cdf20f339f706a3c36ce2')
[winter-forest-7209][2016-06-24 18:22:56,273][ERROR] Error running task in queue
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 251, in run
    self.task()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/init_user_pooled.py", line 24, in task
    self.user.initialize()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/user/user.py", line 225, in initialize
    utils.rmtree(temp_path)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 198, in rmtree
    check_output_logged(['rm', '-rf', path])
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  queue_type = u'init_user_pooled'
  queue_id   = ObjectId('576db2bff339f7036f721c01')
[winter-forest-7209][2016-06-24 20:48:06,825][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-24 20:49:12,221][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-24 20:51:08,356][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-24 20:53:04,478][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-25 01:18:15,073][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576ce23af339f706a3c3767b')
[winter-forest-7209][2016-06-25 01:18:15,116][ERROR] Unexpected loss of iptables rule, adding again...
  rule = ['FORWARD', '-o', 'tun1', '-j', 'ACCEPT']
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 588, in upsert_rules
    rule=rule,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[winter-forest-7209][2016-06-25 01:18:15,129][ERROR] Failed to insert iptables rule, retrying...
  rule = ['FORWARD', '-o', 'tun1', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_576d31b4f339f706a3c46e2d']
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 590, in upsert_rules
    self._insert_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 544, in _insert_iptables_rule
    rule=rule,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[winter-forest-7209][2016-06-25 01:18:16,750][ERROR] Failed to insert iptables rule, retrying...
  rule = ['FORWARD', '-o', 'tun1', '-j', 'ACCEPT', '-m', 'comment', '--comment', 'pritunl_576d31b4f339f706a3c46e2d']
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 590, in upsert_rules
    self._insert_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 544, in _insert_iptables_rule
    rule=rule,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[winter-forest-7209][2016-06-25 01:18:18,224][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 590, in upsert_rules
    self._insert_iptables_rule(rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 536, in _insert_iptables_rule
    ['ip6tables' if ipv6 else 'iptables', '-I'] + rule)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-25 01:18:18,621][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576ce23af339f706a3c3767b')
[winter-forest-7209][2016-06-25 01:18:20,151][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-25 01:18:20,689][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576ce23af339f706a3c3767b')
[winter-forest-7209][2016-06-25 01:18:21,715][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-25 01:18:22,269][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576ce23af339f706a3c3767b')
[winter-forest-7209][2016-06-25 01:18:23,330][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576d31b4f339f706a3c46e2d')
[winter-forest-7209][2016-06-25 01:18:23,515][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 640, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 582, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 502, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('576ce23af339f706a3c3767b')
[winter-forest-7209][2016-06-25 01:38:10,493][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 152, in check_output_logged
    return_code, cmd, output=stdoutdata)
CalledProcessError: Command '['free']' returned non-zero exit status -11
[winter-forest-7209][2016-06-25 01:38:10,482][ERROR] Popen returned error exit code
  cmd         = ['free']
  return_code = -11
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/helpers.py", line 39, in _wrapped
    for _ in call(*args, **kwargs):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/runners/host.py", line 37, in _keep_alive_thread
    mem_usage = host.usage_utils.get_mem_usage()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 148, in check_output_logged
    stderr=stderrdata,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[winter-forest-7209][2016-06-25 05:26:03,658][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 135, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[winter-forest-7209][2016-06-25 05:31:06,545][INFO] Server restarting...
[winter-forest-7209][2016-06-25 05:31:06,551][INFO] Starting server
[winter-forest-7209][2016-06-25 05:31:09,532][INFO] Server restarting...
[winter-forest-7209][2016-06-25 05:31:09,535][INFO] Starting server
[winter-forest-7209][2016-06-25 06:49:45,591][INFO] Starting server
[winter-forest-7209][2016-06-25 09:48:30,084][INFO] Starting server

_______________________________________________
![photo_2016-06-25_21-58-32](https://cloud.githubusercontent.com/assets/20129355/16357136/d4040afc-3b20-11e6-9035-f5bc57cad332.jpg)

**Comment by zachhuff386** [comment]
The server does not have enough memory.
