### ISSUE TITLE
Can't access configuration panel after installation | Ubuntu 14.04

### ISSUE THREAD

**Issue by dionkoffie** [pritunl/pritunl#384]
Hello,

I've been trying to install pritunl for the past couple hours, but it doesn't seem to work. 
I Installed everything correctly according to the pritunl website.

Like this:
$ nano /etc/apt/sources.list.d/mongodb-org-3.0.list
deb http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.0 multiverse

$ nano /etc/apt/sources.list.d/pritunl.list
deb http://repo.pritunl.com/stable/apt trusty main

$ apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 7F0CEB10
$ apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv CF8E292A
$ apt-get update
$ apt-get install pritunl mongodb-org
$ service pritunl start

After that I go my browser and navigate to https://MYSERVERIP/
It then asks me for the pritunl-key and the mongod URI (which is mongodb://localhost:27017/pritunl )

After that I click save and nothing happens then. I get disconnected from the website (see: http://i.imgur.com/0e1EYxB.png )

Is there any way to fix this? I'm ready to trow my server out of the window now. 

Thanks!

**Comment by xUmaRix** [comment]
Me too.

From the log I saw

```
[undefined][2016-06-27 16:57:49,573][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.24.1019.25-py2.7.egg/pritunl/setup/__init__.py", line 33, in setup_all
    setup_mongo()
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.24.1019.25-py2.7.egg/pritunl/setup/mongo.py", line 153, in setup_mongo
    settings.init()
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.24.1019.25-py2.7.egg/pritunl/settings/settings.py", line 125, in init
    self.commit(True)
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.24.1019.25-py2.7.egg/pritunl/settings/settings.py", line 90, in commit
    messenger.publish('setting', docs, transaction=tran)
  File "/usr/local/lib/python2.7/dist-packages/pritunl-1.24.1019.25-py2.7.egg/pritunl/messenger.py", line 10, in publish
    if cache.has_cache:
AttributeError: 'module' object has no attribute 'has_cache'

```

**Comment by zachhuff386** [comment]
Check the output of `pritunl logs` and `cat /var/log/pritunl.log`. The setup failed error above is from improperly installing Pritunl, none of the packages should install anything in `/usr/local`. Use the installation instructions on the homepage.

**Comment by dionkoffie** [comment]
Where should I install it then? It doesn't say where.

**Comment by zachhuff386** [comment]
Not enough information was provided to solve this issue.
