### ISSUE TITLE
Unknown server error occurred. Ubuntu 14.04

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#385]
Unknown server error occurred. Ubuntu 14.04

https://gyazo.com/2532d7fbdeffae89d013db2669e5f860

**Comment by zachhuff386** [comment]
Check the output of `pritunl logs` and `cat /var/log/pritunl.log`.

**Comment by US9IDX** [comment]
```
[undefined][2016-06-27 05:46:17,677][INFO] Starting setup server
[undefined][2016-06-27 05:46:17,678][INFO] Generating setup server ssl cert
[undefined][2016-06-27 05:46:42,624][INFO] Starting setup server
[undefined][2016-06-27 05:46:42,626][INFO] Generating setup server ssl cert
[undefined][2016-06-27 05:47:57,748][INFO] Running 1.24 database upgrade
[undefined][2016-06-27 05:47:58,281][ERROR] Server upgrade failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 209, in _upgrade_thread
    upgrade.upgrade_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/upgrade/__init__.py", line 48, in upgrade_server
    upgrade_1_24()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/upgrade/upgrade_1_24.py", line 20, in upgrade_1_24
    if DUO_AUTH in sso:
TypeError: argument of type 'NoneType' is not iterable
[undefined][2016-06-27 05:47:58,285][INFO] Stopping server
[undefined][2016-06-27 05:53:14,176][INFO] Starting setup server
[undefined][2016-06-27 05:53:19,105][INFO] Running 1.24 database upgrade
[undefined][2016-06-27 05:53:19,204][ERROR] Server upgrade failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/server.py", line 209, in _upgrade_thread
    upgrade.upgrade_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/upgrade/__init__.py", line 48, in upgrade_server
    upgrade_1_24()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/upgrade/upgrade_1_24.py", line 20, in upgrade_1_24
    if DUO_AUTH in sso:
TypeError: argument of type 'NoneType' is not iterable
[undefined][2016-06-27 05:53:19,207][INFO] Stopping server
```

**Comment by zachhuff386** [comment]
Run `pritunl reset-version`

**Comment by US9IDX** [comment]
```
[undefined][2016-06-27 05:56:38,206][INFO] Setting db version
  new_ver = '1.24.1019.25'
  cur_ver = u'1.23.1005.91'
Database version reset to 1.24.1019.25

```

**Comment by zachhuff386** [comment]
The server will work after restarting the service.

**Comment by US9IDX** [comment]
service pritunl restart
--
Internal Server Error

**Comment by zachhuff386** [comment]
Reboot the server.

**Comment by US9IDX** [comment]
Error 500

root@digitalocean:~# pritunl reset-version
Database version reset to 1.24.1019.25

**Comment by US9IDX** [comment]
Port 9700

**Comment by US9IDX** [comment]
{
    "mongodb_uri": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX", 
    "log_path": "/var/log/pritunl.log", 
    "static_cache": true, 
    "temp_path": "/tmp/pritunl_485c1055e64a4ba18357d1ee0114a38e", 
    "bind_addr": "0.0.0.0", 
    "debug": false, 
    "www_path": "/usr/share/pritunl/www", 
    "local_address_interface": "auto", 
    "port": 443
}

**Comment by US9IDX** [comment]
How to renew the old More versions?

**Comment by US9IDX** [comment]
v1.24.1019.41 and bug.
error 500
