### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by US9IDX** [pritunl/pritunl#387]
Unknown server error occurred. Ubuntu 14.04

```
[undefined][2016-05-18 12:59:04,293][INFO] Starting setup server
[undefined][2016-05-18 12:59:04,297][INFO] Generating setup server ssl cert
[undefined][2016-06-11 08:17:29,309][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/server.py", line 239, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 102, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 92, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 744, in _send_message_with_response
    exhaust)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 755, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/server.py", line 83, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/server.py", line 102, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 511, in get_socket
    sock_info.check_auth(all_credentials)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 276, in check_auth
    auth.authenticate(credentials, self)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 407, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 389, in _authenticate_default
    return _authenticate_mongo_cr(credentials, sock_info)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 382, in _authenticate_mongo_cr
    sock_info.command(source, query)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 184, in command
    codec_options, check, allowable_errors)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/network.py", line 54, in command
    helpers._check_command_response(response_doc, msg, allowable_errors)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/helpers.py", line 188, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('authenticate', 1), ('user', u'pritunl'), ('nonce', u'b207f9e782103567'), ('key', u'5c4c195280c261ee76101be5fdef1900')]) on namespace pritunl.$cmd failed: auth failed
[undefined][2016-06-11 08:17:59,341][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/server.py", line 239, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 102, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 92, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 744, in _send_message_with_response
    exhaust)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 755, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/server.py", line 83, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/server.py", line 102, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 511, in get_socket
    sock_info.check_auth(all_credentials)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 276, in check_auth
    auth.authenticate(credentials, self)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 407, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 389, in _authenticate_default
    return _authenticate_mongo_cr(credentials, sock_info)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 382, in _authenticate_mongo_cr
    sock_info.command(source, query)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 184, in command
    codec_options, check, allowable_errors)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/network.py", line 54, in command
    helpers._check_command_response(response_doc, msg, allowable_errors)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/helpers.py", line 188, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('authenticate', 1), ('user', u'pritunl'), ('nonce', u'85d20bfb83827cbb'), ('key', u'7cff485c91b03bc6828ea66f17544de4')]) on namespace pritunl.$cmd failed: auth failed
[undefined][2016-06-11 08:18:29,914][ERROR] Error connecting to mongodb server
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/server.py", line 239, in setup_server
    db_ver_int = utils.get_db_ver_int()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 102, in get_db_ver_int
    version = get_db_ver()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/utils/misc.py", line 92, in get_db_ver
    '_id': 'version',
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/collection.py", line 798, in find_one
    for result in cursor.limit(-1):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 977, in next
    if len(self.__data) or self._refresh():
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 902, in _refresh
    self.__read_preference))
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/cursor.py", line 813, in __send_message
    **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 744, in _send_message_with_response
    exhaust)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/mongo_client.py", line 755, in _reset_on_error
    return func(*args, **kwargs)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/server.py", line 83, in send_message_with_response
    with self.get_socket(all_credentials, exhaust) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/server.py", line 102, in get_socket
    with self.pool.get_socket(all_credentials, checkout) as sock_info:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 511, in get_socket
    sock_info.check_auth(all_credentials)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 276, in check_auth
    auth.authenticate(credentials, self)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 407, in authenticate
    auth_func(credentials, sock_info)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 389, in _authenticate_default
    return _authenticate_mongo_cr(credentials, sock_info)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/auth.py", line 382, in _authenticate_mongo_cr
    sock_info.command(source, query)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/pool.py", line 184, in command
    codec_options, check, allowable_errors)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/network.py", line 54, in command
    helpers._check_command_response(response_doc, msg, allowable_errors)
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pymongo/helpers.py", line 188, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
OperationFailure: command SON([('authenticate', 1), ('user', u'pritunl'), ('nonce', u'd8df0de657533a82'), ('key', u'75285949daf1e94866adde7b865a248c')]) on namespace pritunl.$cmd failed: auth failed
[undefined][2016-06-11 08:18:46,717][INFO] Stopping server
[undefined][2016-06-15 14:20:48,893][ERROR] Database version is newer than server version
  db_version     = 1002310054091
  server_version = 1002310024028
[undefined][2016-06-15 14:20:48,894][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 32, in setup_all
    setup_server()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/server.py", line 255, in setup_server
    exit(75)
  File "/usr/lib/pritunl/lib64/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: 75
[undefined][2016-06-28 03:40:34,133][ERROR] Database version is newer than server version
  db_version     = 1002410194041
  server_version = 1002310054091
[undefined][2016-06-28 03:40:34,134][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 32, in setup_all
    setup_server()
  File "/usr/lib/pritunl/lib/python2.7/site-packages/pritunl/setup/server.py", line 254, in setup_server
    exit(75)
  File "/usr/lib/pritunl/lib64/python2.7/site.py", line 403, in __call__
    raise SystemExit(code)
SystemExit: 75

```

Database version reset to 1.24.1019.41

**Comment by US9IDX** [comment]
https://gyazo.com/7a4226931e60bc93b7aa0dd110808ae5

**Comment by zachhuff386** [comment]
All Pritunl servers connecting to a database must be the same version. When downgrading run the command `pritunl reset-version` then restart the service.

**Comment by US9IDX** [comment]
All servers Database version reset to 1.24.1019.41

I have installed various versions of OS CentOS 7 and Ubuntu 14.04. The error is the same. I tried to do it on different servers.

I urgently need help, since my service is not working !!!

**Comment by zachhuff386** [comment]
The server version above is 1.23

**Comment by US9IDX** [comment]
1.23 How do I install?

**Comment by US9IDX** [comment]
I installed version 1.23, but now the error due to incompatibility ydannyh bases.
