### ISSUE TITLE
[ERROR] Error in management socket thread

### ISSUE THREAD

**Issue by kitketxss** [pritunl/pritunl#396]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 246, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 328, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
  instance_id = ObjectId('577693c518eadc0a193df3e9')
  socket_path = '/var/run/pritunl_577693c518eadc0a193df3e9.sock'
  server_id   = ObjectId('5776935a18eadc0a193df2a6')

**Comment by kitketxss** [comment]
debian 7 64bit problem this...

**Comment by zachhuff386** [comment]
Check the logs in the top right or run the command `pritunl logs`

**Comment by kitketxss** [comment]
[summer-skies-5774][2016-07-02 07:49:34,377][ERROR] Error in management socket thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 246, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 328, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
  instance_id = ObjectId('5777720068ce190a0aaa6507')
  socket_path = '/var/run/pritunl_5777720068ce190a0aaa6507.sock'
  server_id   = ObjectId('577770ff68ce190a0aaa621f')

**Comment by kitketxss** [comment]
how to fix it? debian 7.10 64bit(digital ocean), In openvpn TCP.
http://prntscr.com/bnt1cm

**Comment by zachhuff386** [comment]
Copy the logs to the issue response.

**Comment by kitketxss** [comment]
[undefined][2016-07-03 04:35:41,969][INFO] Starting setup server
[undefined][2016-07-03 04:35:41,974][INFO] Generating setup server ssl cert
[thawing-meadow-2666][2016-07-03 04:37:18,940][INFO] Starting server
[thawing-meadow-2666][2016-07-03 04:37:18,942][INFO] Generating server dh params...
[thawing-meadow-2666][2016-07-03 04:37:20,952][INFO] Generating server certificate...
[thawing-meadow-2666][2016-07-03 04:40:32,626][ERROR] Server management socket path not found
  instance_id = ObjectId('57789734bad9490c8582a9db')
  socket_path = '/var/run/pritunl_57789734bad9490c8582a9db.sock'
  server_id   = ObjectId('577896f2bad9490c8582a93f')
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 525, in __bootstrap
    self.__bootstrap_inner()
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 246, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 326, in connect
    self.wait_for_socket()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 178, in wait_for_socket
    socket_path=self.socket_path,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/logger/__init__.py", line 55, in error
    kwargs['traceback'] = traceback.format_stack()
[thawing-meadow-2666][2016-07-03 04:40:32,628][ERROR] Error in management socket thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 246, in _socket_thread
    self.connect()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance_com.py", line 328, in connect
    self.sock.connect(self.socket_path)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 2] No such file or directory
  instance_id = ObjectId('57789734bad9490c8582a9db')
  socket_path = '/var/run/pritunl_57789734bad9490c8582a9db.sock'
  server_id   = ObjectId('577896f2bad9490c8582a93f')

can u fix it? or digital ocean problem?
debian 7 64bit on pritunl TCP only...

**Comment by zachhuff386** [comment]
What is shown in the server output

**Comment by kitketxss** [comment]
[guarded-waves-5477] Options error: --mode server currently only supports --proto udp or --proto tcp-server or proto tcp6-server
[guarded-waves-5477] Use --help for more information.

**Comment by kitketxss** [comment]
they say tht... pls help us.
