### ISSUE TITLE
server error proxy error 500

### ISSUE THREAD

**Issue by Dewa-ubuntu** [pritunl/pritunl#403]
server error..
[pakatan-harapan][2016-07-06 13:31:04,824][ERROR] Server error occurred
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 200, in _run_server
    app_server.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1937, in start
    raise socket.error(msg)
error: No socket could be created -- (('127.0.0.1', 9756): [Errno 98] Address already in use)
Traceback (most recent call last):
  File "/usr/lib/pritunl/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.24.1025.78', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 258, in main
    pritunl.init_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__init__.py", line 21, in init_server
    app.run_server()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 282, in run_server
    _run_wsgi()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 219, in _run_wsgi
    _run_server(restart)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/app.py", line 200, in _run_server
    app_server.start()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1937, in start
    raise socket.error(msg)
socket.error: No socket could be created -- (('127.0.0.1', 9756): [Errno 98] Address already in use)

**Comment by zachhuff386** [comment]
Are you attempting to run more then one instance of Pritunl on one server? What other errors are occurring?
