### ISSUE TITLE
Adding/ downloading users

### ISSUE THREAD

**Issue by VPNGhost** [pritunl/pritunl#409]
When adding bulk users it adds some maybe gets anywhere from 100-1000 added
 then give a server error message, so i click the cancel button to close the Bulk user add
when i refresh the page i see the user number is still climbing but when i search a couple of the userssome times they will all have duplicates. 
i seem to get this kind of error on multiple ocasions trying to add bulk users
it is a real pain adding tons of users one by one.

any suggestions on a solution?

Also is there any methods to bulk download user profiles as well?

**Comment by zachhuff386** [comment]
Closing the bulk user dialog won't stop the bulk add user process. What errors are in the logs?

**Comment by VPNGhost** [comment]
ok good to know it continues when the dialog box is closed.

[restless-fields-9472][2016-07-12 22:08:28,137][ERROR] Exception on /user/57816489fbd8f516ef8f5d27 [POST]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 10, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/user.py", line 273, in user_post
    dns_suffix=dns_suffix, port_forwarding=port_forwarding)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/organization/organization.py", line 351, in new_user
    block=block, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/utils.py", line 49, in reserve
    return reserve_types[reserve_type](*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queues/init_user_pooled.py", line 82, in reserve_queued_user
    doc = QueueInitUserPooled.reserve(reserve_id, reserve_data, block=block)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/queue/queue.py", line 219, in reserve
    'queue_type': doc['type'],
QueueTimeout: Blocking queue reserve timed out. {'queue_type': u'init_user_pooled', 'queue_id': ObjectId('57854e1bfbd8f516ef9c0358')}

**Comment by zachhuff386** [comment]
This has been fixed
