### ISSUE TITLE
[ERROR] Exception on /auth/session [POST]

### ISSUE THREAD

**Issue by billxinli** [pritunl/pritunl#414]
I followed 16.04 LTS install instructions. However I am seeing the following error:

```
[ERROR] Exception on /auth/session [POST]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/auth/app.py", line 17, in _wrapped
    return call(*args, **kwargs)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/auth.py", line 228, in auth_session_post
    if RADIUS_AUTH in settings.app.sso:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by zachhuff386** [comment]
This would have returned invalid username. The default username/password is `pritunl`

**Comment by billxinli** [comment]
Not sure If I didn't read the manual. However, I was able to login with pritunl, then change to admin/password. I went in and created a user. 

I assume, the user then should be able to login and change their pin and download their profile? However if I login as this newly created user I get:
`500: Internal Server Error` from that end point.

**Comment by zachhuff386** [comment]
Users can't login with pins, pins are for connecting to servers. Single sign-on must be used for authenticating users. Radius and custom plugin can be used for username/password login.

**Comment by billxinli** [comment]
Gotta, thanks.
