### ISSUE TITLE
Pritunl web stops accepting connections

### ISSUE THREAD

**Issue by pedroagabreu** [pritunl/pritunl#420]
Version: v1.24.1019.41

I have two pritunl hosts on AWS, and I'm using Route53 health checks on each for /login on port 443. Also using Let's Encrypt.

After starting a host the checks are OK for a while, but that never lasts long. From what I can tell, the connection is established but hangs immediately:

> $ openssl s_client -connect localhost:443
CONNECTED(00000003)
^C

Doing a pritunl logs shows this all the time (even when the health check is not yet failing) on both hosts:

> [us1][2016-07-18 08:07:23,424][ERROR] Exception on /login [GET]
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/handlers/static.py", line 113, in login_static_get
    if DUO_AUTH in settings.app.sso:
TypeError: argument of type 'bool' is not iterable

Netstat shows me a bunch of connections from the Route53 health checkers in a SYN_RECV status to port 443:

> tcp        0      0 10.11.11.10:443       107.23.255.12:9209      SYN_RECV
tcp        0      0 10.11.11.10:443       54.248.220.44:13424     SYN_RECV
tcp        0      0 10.11.11.10:443       54.248.220.44:29260     SYN_RECV
tcp        0      0 10.11.11.10:443       54.243.31.236:20850     SYN_RECV

Port 80 responds with a 301 as it should.

Could the connections from the health checkers be triggering something that eventually floors pritunl-web?

**Comment by zachhuff386** [comment]
This was an issue with the pritunl-web Go server it was fixed in a previous release.

**Comment by pedroagabreu** [comment]
Upgraded yesterday to v1.25.1039.56.

Today it was dead again. This time, openssl actually shows the certificates but it hangs on the GET /login...

**Comment by pedroagabreu** [comment]
This is the only error I see in pritunl logs. Only started hanging on /login seven hours after this.

> [eu1][2016-07-19 02:06:21,363][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 44, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
InvalidId: u'LocalIndex.html' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
  object_id = u'LocalIndex.html'

**Comment by zachhuff386** [comment]
What is the out of ```sudo lsof -p `pgrep pritunl-web` | wc -l``` and ```sudo lsof -p `pgrep pritunl | sed -n 1p` | wc -l```

**Comment by pedroagabreu** [comment]
```
# lsof -p `pgrep pritunl-web` | wc -l
2437
# lsof -p `pgrep pritunl | sed -n 1p` | wc -l
57
```

The pritunl-web close waits seem to be all from the amazon health checkers. But over 1700 of those are:

> pritunl-w 18820 root 1748u  sock      0,7      0t0 17535693 can't identify protocol

...And growing.

**Comment by zachhuff386** [comment]
There shouldn't be an open connection issue in v1.25. What is `pritunl --version` showing? Was the service restarted after upgrading? Raising the open file limit should fix any other issues.

**Comment by pedroagabreu** [comment]
> pritunl v1.25.1041.8

Yes, restarted.

I'm gonna check the open file limit.

**Comment by pedroagabreu** [comment]
This is the upstart script being used, I believe it's the default:

> description "Pritunl Daemon"
limit nofile 50000 50000
start on runlevel [2345]
stop on runlevel [!2345]
exec pritunl start

**Comment by zachhuff386** [comment]
Check the logs a warning will be shown if ulimits are low

**Comment by pedroagabreu** [comment]
Only one error in the logs today:

> [eu1][2016-07-20 02:08:21,900][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 44, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
InvalidId: u'LocalIndex.html' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
  object_id = u'LocalIndex.html'

**Comment by pedroagabreu** [comment]
Looking at the other host that has this problem much less for some reason, it had an outage tonight of EXACTLY three hours, 4h05 to 7h05. Recovered by itself. I see a couple of (automatic) restarts that much have fixed it, UTC time:

> [us1][2016-07-20 11:10:11,941][INFO] Server restarting...
[us1][2016-07-20 11:10:11,941][INFO] Starting server
[us1][2016-07-20 11:10:14,945][INFO] Server restarting...
[us1][2016-07-20 11:10:14,945][INFO] Starting server
