### ISSUE TITLE
Please FIX this For Debian 64bit DO

### ISSUE THREAD

**Issue by kitketxss** [pritunl/pritunl#421]
after i open web
http://image.prntscr.com/image/ed1646008bb9405fb0c45805e116a6fc.png

Starting service...
Service started
root@debian-512mb-sgp1-01:~# Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:140A1175:SSL routines:SSL_BYTES_TO_CIPHER_LIST:inappropriate fallback
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:140A1175:SSL routines:SSL_BYTES_TO_CIPHER_LIST:inappropriate fallback
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
Error in HTTPServer.tick
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 1950, in start
    self.tick()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/wsgiserver2.py", line 2017, in tick
    s, ssl_env = self.ssl_adapter.wrap(s)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/wsgiserver/ssl_builtin.py", line 57, in wrap
    ssl_version=ssl.PROTOCOL_SSLv23)
  File "/usr/lib/python2.7/ssl.py", line 381, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 143, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 305, in do_handshake
    self._sslobj.do_handshake()
SSLError: [Errno 1] _ssl.c:504: error:140A1175:SSL routines:SSL_BYTES_TO_CIPHER_LIST:inappropriate fallback

**Comment by zachhuff386** [comment]
I can't replicate this issue. Run the command `pritunl reset-ssl-cert`

**Comment by kitketxss** [comment]
root@debian-512mb-sgp1-01:~# pritunl reset-ssl-cert
[undefined][2016-07-18 22:10:47,191][ERROR] Pritunl setup failed
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 63, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 53, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 308, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 225, in split_hosts
    raise ConfigurationError("Empty host "
ConfigurationError: Empty host (or extra comma in host list).
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.25.1039.56', 'console_scripts', 'pritunl')()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/__main__.py", line 195, in main
    setup.setup_db()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/__init__.py", line 63, in setup_db
    setup_mongo()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/setup/mongo.py", line 53, in setup_mongo
    connectTimeoutMS=MONGO_CONNECT_TIMEOUT,
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/mongo_client.py", line 308, in __init__
    seeds.update(uri_parser.split_hosts(entity, port))
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pymongo/uri_parser.py", line 225, in split_hosts
    raise ConfigurationError("Empty host "
pymongo.errors.ConfigurationError: Empty host (or extra comma in host list).
root@debian-512mb-sgp1-01:~#
