### ISSUE TITLE
Problem need settle

### ISSUE THREAD

**Issue by kitketxss** [pritunl/pritunl#424]
[thriving-thunder-5466][2016-07-20 22:27:06,756][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-20 22:28:00,375][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-20 23:12:04,072][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-20 23:49:01,901][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-20 23:50:39,373][ERROR] Error in iptables thread
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/server/instance.py", line 717, in _iptables_thread
    self.iptables.upsert_rules(log=True)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 590, in upsert_rules
    if not self._exists_iptables_rule(rule):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/iptables.py", line 510, in _exists_iptables_rule
    stderr=subprocess.PIPE,
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  server_id = ObjectId('578e1e4118eadc0b2962f0c3')
[thriving-thunder-5466][2016-07-21 00:24:05,852][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-21 00:54:10,818][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-21 02:28:01,712][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-21 02:29:06,013][ERROR] Failed to get memory usage
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/host/usage_utils.py", line 64, in get_mem_usage
    free = utils.check_output_logged(['free']).split()
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 150, in check_output_logged
    *args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1223, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
[thriving-thunder-5466][2016-07-21 05:06:27,340][INFO] Starting server
[thriving-thunder-5466][2016-07-21 05:06:30,106][INFO] Recovering server state
  server_id      = ObjectId('578e1e4118eadc0b2962f0c3')
  prefered_hosts = [u'143ea7c088d34231861b7e8e3ebc362b']
[undefined][2016-07-21 05:09:36,918][INFO] Setting db version
  cur_min_ver = u'1.25.0.0'
  new_ver     = '1.25.1042.81'
  new_min_ver = '1.25.0.0'
  cur_ver     = u'1.25.1034.83snapshot'
[thriving-thunder-5466][2016-07-21 05:09:38,241][INFO] Starting server
[thriving-thunder-5466][2016-07-21 05:09:40,274][INFO] Recovering server state
  server_id      = ObjectId('578e1e4118eadc0b2962f0c3')
  prefered_hosts = [u'143ea7c088d34231861b7e8e3ebc362b']
[thriving-thunder-5466][2016-07-21 08:01:51,924][ERROR] Failed to convert object id
Traceback (most recent call last):
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/pritunl/utils/misc.py", line 44, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 110, in __init__
    self.__validate(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 206, in __validate
    _raise_invalid_id(oid)
  File "/usr/lib/pritunl/local/lib/python2.7/site-packages/bson/objectid.py", line 52, in _raise_invalid_id
    " or a 24-character hex string" % oid)
InvalidId: u'Profile.aspx' is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
  object_id = u'Profile.aspx'

**Comment by zachhuff386** [comment]
The memory usage monitoring has been fixed. Snapshot releases should not be used for production servers. The last error is from an invalid HTTP request.
