### ISSUE TITLE
Unable to connect unless restart server.

### ISSUE THREAD

**Issue by FireUponSky** [pritunl/pritunl#58]
Here is my problem. I use TCP protocol and pull the port to another server with obfsproxy. It used to work fine. However, after recent update, I have to restart the server every time I want to connect or it just failed here:

Server logs:
<pre><code>
[snowy-waves-1004] Thu Jan  1 07:53:31 2015 us=221225 127.0.0.1:51337 [54a12ab4f56ec216de80e869] Peer Connection Initiated with [AF_INET]127.0.0.1:51337
[snowy-waves-1004] Thu Jan  1 07:53:33 2015 us=88102 127.0.0.1:51337 PUSH: Received control message: 'PUSH_REQUEST'
[snowy-waves-1004] Thu Jan  1 07:53:37 2015 us=495252 127.0.0.1:51337 PUSH: Received control message: 'PUSH_REQUEST'
[snowy-waves-1004] Thu Jan  1 07:53:43 2015 us=50044 127.0.0.1:51337 PUSH: Received control message: 'PUSH_REQUEST'
[snowy-waves-1004] Thu Jan  1 07:53:47 2015 us=532217 127.0.0.1:51337 PUSH: Received control message: 'PUSH_REQUEST'
[snowy-waves-1004] Thu Jan  1 07:53:47 2015 us=688763 127.0.0.1:51337 Connection reset, restarting [0]
[snowy-waves-1004] Thu Jan  1 07:53:47 2015 us=688811 127.0.0.1:51337 SIGUSR1[soft,connection-reset] received, client-instance restarting
</code></pre>

client logs:
<pre><code>
Thu Jan 01 21:56:41 2015 10 variation(s) on previous 3 message(s) suppressed by --mute
Thu Jan 01 21:56:41 2015 [54a20303f56ec20349515fac] Peer Connection Initiated with [AF_INET]xxx.xxx.xxx.xxx:xxxx
Thu Jan 01 21:57:34 2015 AUTH: Received control message: AUTH_FAILED
Thu Jan 01 21:57:34 2015 SIGUSR1[soft,auth-failure] received, process restarting
</code></pre>

after restart the server on pritunl manage page I can successfully connect for once. I also find that after the client disconnected, user still have "connected" status on the manage page, I guess this is related to the problem.

Any suggestion?

**Comment by matthewgall** [comment]
Can confirm affecting my installations.

Server logs:
```
[summer-plateau-8314] Thu Jan  1 21:50:24 2015 us=89898 2.97.132.216:55034 [54a48f5d00677903bfaed646] Peer Connection Initiated with [AF_INET]2.97.132.216:55034
[summer-plateau-8314] Thu Jan  1 21:50:26 2015 us=744531 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:50:31 2015 us=636786 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:50:36 2015 us=199743 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:50:41 2015 us=881524 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:50:46 2015 us=124586 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:50:51 2015 us=178114 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:50:56 2015 us=359153 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
[summer-plateau-8314] Thu Jan  1 21:51:01 2015 us=635390 2.97.132.216:55034 PUSH: Received control message: 'PUSH_REQUEST'
```

**Comment by zachhuff386** [comment]
This is most likely related to the `ServerInstanceCom` encountering an error and failing to respond to client requests. Check the command `pritunl logs` for errors.

**Comment by matthewgall** [comment]
As requested:

'''
[summer-plateau-8314][2015-01-01 21:52:42,622][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a5c0fc00677903bfafb92d')
  server_id   = ObjectId('54a48fac00677903bfaed701')
  line        = '>CLIENT:ENV,END'
[summer-plateau-8314][2015-01-01 21:52:55,721][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a5c0fc00677903bfafb92d')
  server_id   = ObjectId('54a48fac00677903bfaed701')
  line        = '>CLIENT:ENV,END'
'''

**Comment by FireUponSky** [comment]
My logs:

`pritunl logs`
<pre><code>
[snowy-waves-1004][2015-01-01 08:56:33,600][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a54269f56ec2076e23d792')
  server_id   = ObjectId('54a523f1f56ec20350b7de0e')
  line        = '>CLIENT:ENV,END'
[snowy-waves-1004][2015-01-01 08:56:45,444][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a54269f56ec2076e23d792')
  server_id   = ObjectId('54a523f1f56ec20350b7de0e')
  line        = '>CLIENT:ENV,END'
[snowy-waves-1004][2015-01-01 08:57:38,579][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a54269f56ec2076e23d792')
  server_id   = ObjectId('54a523f1f56ec20350b7de0e')
  line        = '>CLIENT:ENV,END'
[snowy-waves-1004][2015-01-01 08:57:51,911][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a54269f56ec2076e23d792')
  server_id   = ObjectId('54a523f1f56ec20350b7de0e')
  line        = '>CLIENT:ENV,END'
[snowy-waves-1004][2015-01-01 08:58:06,261][ERROR] Failed to parse line from vpn com
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 472, in _socket_thread
    self.parse_line(line)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 340, in parse_line
    self.client_disconnect(self.client)
  File "/usr/lib/python2.7/dist-packages/pritunl/server/instance_com.py", line 254, in client_disconnect
    user_id = utils.ObjectId(client_id) if client_id else None
  File "/usr/lib/python2.7/dist-packages/pritunl/utils/misc.py", line 41, in ObjectId
    return bson.ObjectId(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 92, in __init__
    self.__validate(oid)
  File "/usr/lib/python2.7/dist-packages/bson/objectid.py", line 199, in __validate
    raise InvalidId("%s is not a valid ObjectId" % oid)
InvalidId: 0 is not a valid ObjectId
  instance_id = ObjectId('54a54269f56ec2076e23d792')
  server_id   = ObjectId('54a523f1f56ec20350b7de0e')
  line        = '>CLIENT:ENV,END'
</code></pre>

**Comment by zachhuff386** [comment]
The commit above will fix this issue, this will be included in the update when it has finished building.
