### ISSUE TITLE
Pritunl Client v1.0.460.45 install on Ubuntu 12.04 broken.

### ISSUE THREAD

**Issue by xamox** [pritunl/pritunl#64]
I installed via ppa.

Got the following error:
```
Traceback (most recent call last):
  File "/usr/bin/pycompile", line 290, in <module>
    main()
  File "/usr/bin/pycompile", line 263, in main
    options.force, options.optimize, e_patterns)
  File "/usr/bin/pycompile", line 155, in compile
    for fn, versions_to_compile in filter_files(files, e_patterns, versions):
  File "/usr/bin/pycompile", line 110, in filter_files
    for fn in files:
  File "/usr/share/python/debpython/files.py", line 77, in filter_out_ext
    for fn in files:
  File "/usr/share/python/debpython/namespace.py", line 77, in add_namespace_files
    for fn in files:
  File "/usr/share/python/debpython/files.py", line 69, in filter_public
    f
or fn in files:
  File "/usr/share/python/debpython/files.py", line 53, in from_package
    raise Exception("cannot get content of %s" % package_name)
Exception: cannot get content of pritunl_client
```

When I tried starting it from the launcher it wouldn't work, from the command line it said the following file didn't exist: /home/xamox/.config/pritunl_client/pritunl_client.log

The fix was:
```
mkdir -p /home/xamox/.config/pritunl_client/
touch /home/xamox/.config/pritunl_client/pritunl_client.log
```

then I could start the client.

**Comment by zachhuff386** [comment]
Fixed in commits below the first error may cause issues with auto-starting VPN profiles which can be fixed by running `sudo mkdir -p /etc/pritunl_client`

https://github.com/pritunl/pritunl-client/commit/0141171ec443b937312b61bea7b29d7fb24a77a4
https://github.com/pritunl/pritunl-client/commit/6d24c2bf81752d5b2204e9377482a1bd4cbd7282

**Comment by xamox** [comment]
Thanks for the extremely fast response time.
