### ISSUE TITLE
Failed to load server status, server error occurred

### ISSUE THREAD

**Issue by texnoid** [pritunl/pritunl#88]
3.16.0-33-generic #44-Ubuntu SMP x86_64 GNU/Linux
pritunl v1.0.544.74
python2.7
#
pritunl logs
Traceback (most recent call last):
  File "/usr/bin/pritunl", line 9, in <module>
    load_entry_point('pritunl==1.0.544.74', 'console_scripts', 'pritunl')()
  File "/usr/lib/python2.7/dist-packages/pritunl/__main__.py", line 101, in main
    print log_view.get_log_lines(options.limit)
  File "/usr/lib/python2.7/dist-packages/pritunl/logger/view.py", line 80, in get_log_lines
    ])['result']
TypeError: 'CommandCursor' object has no attribute '__getitem__'

**Comment by zachhuff386** [comment]
This issue is from api changes in pymongo 3.0 and will be fixed in the next release.
